### ISSUE TITLE
pd-ctl hungs on notty ssh session 

### ISSUE THREAD

**Issue by overvenus** [tikv/pd#3318]
## Bug Report

pd-ctl hungs on notty ssh session.

```bash
ssh remote 'pd-ctl tso 420424879248244737'
```

<details> <summary> go routines </summary>

```
goroutine 193 [running]:
runtime/pprof.writeGoroutineStacks(0x106ff00, 0xc0003a0000, 0x0, 0x0)
	/home/stn/.local/go/src/runtime/pprof/pprof.go:679 +0x9d
runtime/pprof.writeGoroutine(0x106ff00, 0xc0003a0000, 0x2, 0x6807f9c0, 0x9af5caf2f254739c)
	/home/stn/.local/go/src/runtime/pprof/pprof.go:668 +0x44
runtime/pprof.(*Profile).WriteTo(0x17512c0, 0x106ff00, 0xc0003a0000, 0x2, 0xc0003a0000, 0xd)
	/home/stn/.local/go/src/runtime/pprof/pprof.go:329 +0x3da
net/http/pprof.handler.ServeHTTP(0xc000396011, 0x9, 0x1090980, 0xc0003a0000, 0xc000386100)
	/home/stn/.local/go/src/net/http/pprof/pprof.go:245 +0x33a
net/http/pprof.Index(0x1090980, 0xc0003a0000, 0xc000386100)
	/home/stn/.local/go/src/net/http/pprof/pprof.go:268 +0x6f1
net/http.HandlerFunc.ServeHTTP(0xf759d0, 0x1090980, 0xc0003a0000, 0xc000386100)
	/home/stn/.local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x1767ac0, 0x1090980, 0xc0003a0000, 0xc000386100)
	/home/stn/.local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0001902a0, 0x1090980, 0xc0003a0000, 0xc000386100)
	/home/stn/.local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000382000, 0x1093040, 0xc00038a000)
	/home/stn/.local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/home/stn/.local/go/src/net/http/server.go:2928 +0x384

goroutine 1 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc000328000, 0x200, 0x45bb30, 0x800000, 0x42e23a)
	/home/stn/.local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x0, 0xc000328000, 0x200, 0x200, 0x0, 0xc000328000, 0xc0002f6780)
	/home/stn/.local/go/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(...)
	/home/stn/.local/go/src/syscall/syscall_unix.go:183
internal/poll.(*FD).Read(0xc0000c6060, 0xc000328000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/home/stn/.local/go/src/internal/poll/fd_unix.go:165 +0x164
os.(*File).read(...)
	/home/stn/.local/go/src/os/file_unix.go:259
os.(*File).Read(0xc00000e010, 0xc000328000, 0x200, 0x200, 0xc000328000, 0x0, 0x0)
	/home/stn/.local/go/src/os/file.go:116 +0x71
bytes.(*Buffer).ReadFrom(0xc00026be38, 0x1070000, 0xc00000e010, 0xc00026be18, 0x4d6a09, 0xf2d94f)
	/home/stn/.local/go/src/bytes/buffer.go:204 +0xb4
io/ioutil.readAll(0x1070000, 0xc00000e010, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stn/.local/go/src/io/ioutil/ioutil.go:36 +0x100
io/ioutil.ReadAll(...)
	/home/stn/.local/go/src/io/ioutil/ioutil.go:45
main.main()
	/home/stn/go/src/github.com/tikv/pd/tools/pd-ctl/main.go:59 +0x389

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/home/stn/.local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/home/stn/.local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/home/stn/.local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 71 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00000df20)
	/home/stn/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:173 +0x3a3
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/stn/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:91 +0x80

goroutine 133 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000290180)
	/home/stn/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:173 +0x3a3
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/stn/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:91 +0x80

goroutine 136 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000290320)
	/home/stn/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:173 +0x3a3
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/stn/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:91 +0x80

goroutine 171 [IO wait]:
internal/poll.runtime_pollWait(0x7f5a253c8e68, 0x72, 0x0)
	/home/stn/.local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000158998, 0x72, 0x0, 0x0, 0xf2ae1b)
	/home/stn/.local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/home/stn/.local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000158980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stn/.local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc000158980, 0xc0000eadb0, 0x732ea4, 0xc000190340)
	/home/stn/.local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00030e6e0, 0x5fed7bd2, 0xc0000eadb0, 0x4c0a16)
	/home/stn/.local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00030e6e0, 0xc0000eae00, 0x18, 0xc000001680, 0x7323d4)
	/home/stn/.local/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc0001902a0, 0x10906c0, 0xc00030e6e0, 0x0, 0x0)
	/home/stn/.local/go/src/net/http/server.go:2896 +0x280
net/http.(*Server).ListenAndServe(0xc0001902a0, 0xc0001902a0, 0x7f5a25408068)
	/home/stn/.local/go/src/net/http/server.go:2825 +0xb7
net/http.ListenAndServe(...)
	/home/stn/.local/go/src/net/http/server.go:3081
main.main.func1()
	/home/stn/go/src/github.com/tikv/pd/tools/pd-ctl/main.go:31 +0x73
created by main.main
	/home/stn/go/src/github.com/tikv/pd/tools/pd-ctl/main.go:30 +0x47

goroutine 180 [chan receive]:
main.main.func2(0xc0002f6a20)
	/home/stn/go/src/github.com/tikv/pd/tools/pd-ctl/main.go:46 +0x52
created by main.main
	/home/stn/go/src/github.com/tikv/pd/tools/pd-ctl/main.go:45 +0x1d7

goroutine 194 [runnable]:
syscall.Syscall(0x0, 0x6, 0xc00037e0d1, 0x1, 0xffffffffffffffff, 0x0, 0xb)
	/home/stn/.local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x6, 0xc00037e0d1, 0x1, 0x1, 0x0, 0x1, 0xc0000e6238)
	/home/stn/.local/go/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(...)
	/home/stn/.local/go/src/syscall/syscall_unix.go:183
internal/poll.(*FD).Read(0xc00037c000, 0xc00037e0d1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/stn/.local/go/src/internal/poll/fd_unix.go:165 +0x164
net.(*netFD).Read(0xc00037c000, 0xc00037e0d1, 0x1, 0x1, 0xfffffffe3bfe3b00, 0x100000001, 0x0)
	/home/stn/.local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000380000, 0xc00037e0d1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/stn/.local/go/src/net/net.go:184 +0x68
net/http.(*connReader).backgroundRead(0xc00037e0c0)
	/home/stn/.local/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/home/stn/.local/go/src/net/http/server.go:673 +0xd4
```

</details>

### What did you expect to see?

No hung.

**Comment by 9547** [comment]
Seems the `pd-ctl` hangs on https://github.com/tikv/pd/blob/974d977598f3f8ded72c0804cb7fefc620007119/tools/pd-ctl/main.go#L54. But I don't think this is a `pd-ctl`'s problem, it should be an SSH problem.

Maybe you can add `-t` to get around this problem:

```bash
ssh -t remote 'pd-ctl tso 420424879248244737`
```

Ref [ssh man page](https://linuxcommand.org/lc3_man_pages/ssh1.html)

>     -t      Force pseudo-terminal allocation.  This can be used to execute arbitrary screen-based programs on a remote machine, which can be very useful, e.g. when implementing menu services.  Multiple -t options force tty allocation, even if ssh has no local tty.


OR echo an empty as pipe input to `pd-ctl`

```bash
ssh remote 'echo | pd-ctl tso 420424879248244737`
```
