### ISSUE TITLE
Data Race in tso tests

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#3399]
### What did you do?

make test

### What did you expect to see?

pass tests

### What did you see instead?

```[2021-01-27T08:21:20.431Z] ==================
[2021-01-27T08:21:20.431Z] WARNING: DATA RACE
[2021-01-27T08:21:20.431Z] Read at 0x00c00e027920 by goroutine 768:
[2021-01-27T08:21:20.431Z]   github.com/tikv/pd/server/region_syncer.(*RegionSyncer).syncRegion()
[2021-01-27T08:21:20.431Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/region_syncer/client.go:103 +0xa9
[2021-01-27T08:21:20.431Z]   github.com/tikv/pd/server/region_syncer.(*RegionSyncer).StartSyncWithLeader.func1()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/region_syncer/client.go:157 +0x6c5
[2021-01-27T08:21:20.432Z] 
[2021-01-27T08:21:20.432Z] Previous write at 0x00c00e027920 by goroutine 524:
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server/region_syncer.(*RegionSyncer).reset()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/region_syncer/client.go:58 +0xe6
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server/region_syncer.(*RegionSyncer).StopSyncWithLeader()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/region_syncer/client.go:42 +0x3c
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server.(*Server).leaderLoop()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/server.go:1162 +0xa93
[2021-01-27T08:21:20.432Z] 
[2021-01-27T08:21:20.432Z] Goroutine 768 (running) created at:
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server/region_syncer.(*RegionSyncer).StartSyncWithLeader()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/region_syncer/client.go:125 +0xc2
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server.(*Server).leaderLoop()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/server.go:1157 +0xb62
[2021-01-27T08:21:20.432Z] 
[2021-01-27T08:21:20.432Z] Goroutine 524 (running) created at:
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server.(*Server).startServerLoop()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/server.go:493 +0x101
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server.(*Server).Run()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/server.go:475 +0x167
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
[2021-01-27T08:21:20.432Z]   fmt.Fscanf()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:143 +0xcf
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:114 +0x192
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
[2021-01-27T08:21:20.432Z]   fmt.Fscanf()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:143 +0xcf
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:114 +0x192
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/db_util.go:52 +0x2f8
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb.openDB()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/db.go:130 +0x9f0
[2021-01-27T08:21:20.432Z]   fmt.(*ss).doScanf()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:1217 +0x382
[2021-01-27T08:21:20.432Z]   fmt.Fscanf()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:143 +0xcf
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:114 +0x192
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
[2021-01-27T08:21:20.432Z]   fmt.Fscanf()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:143 +0xcf
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:114 +0x192
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
[2021-01-27T08:21:20.432Z]   fmt.Fscanf()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:143 +0xcf
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:114 +0x192
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
[2021-01-27T08:21:20.432Z]   fmt.Fscanf()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:143 +0xcf
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:114 +0x192
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/db.go:476 +0xc5
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb.openDB()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/db.go:125 +0x9cc
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb.Open()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/db.go:197 +0x1d3
[2021-01-27T08:21:20.432Z]   fmt.Fscanf()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:143 +0xcf
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/fmt/scan.go:114 +0x192
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/session.go:134 +0xf4
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb.(*session).recover()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/session.go:142 +0x1938
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb.Open()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/db.go:183 +0xf8
[2021-01-27T08:21:20.432Z]   github.com/syndtr/goleveldb/leveldb.OpenFile()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/db.go:219 +0xa5
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server/kv.NewLeveldbKV()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/kv/levedb_kv.go:32 +0x66
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server/core.NewRegionStorage()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/core/region_storage.go:59 +0x5d
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server.(*Server).startServer()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/server.go:372 +0x1072
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/server.(*Server).Run()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/server.go:471 +0xfd
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/tests.(*TestServer).Run()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/tests/cluster.go:100 +0xec
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/tests/server/tso_test.(*testLocalTSOSuite).TestLocalTSOAfterMemberChanged()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/tests/server/tso/local_tso_test.go:178 +0x88d
[2021-01-27T08:21:20.432Z]   github.com/pingcap/failpoint.parseTerm()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200702092429-9f69995143ce/terms.go:148 +0x24d
[2021-01-27T08:21:20.432Z]   github.com/pingcap/failpoint.parse()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200702092429-9f69995143ce/terms.go:125 +0xb4
[2021-01-27T08:21:20.432Z]   github.com/pingcap/failpoint.newTerms()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200702092429-9f69995143ce/terms.go:97 +0x6a
[2021-01-27T08:21:20.432Z]   github.com/pingcap/failpoint.(*Failpoint).Enable()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200702092429-9f69995143ce/failpoint.go:53 +0x53
[2021-01-27T08:21:20.432Z]   github.com/pingcap/failpoint.(*Failpoints).Enable()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200702092429-9f69995143ce/failpoints.go:104 +0x160
[2021-01-27T08:21:20.432Z]   github.com/tikv/pd/tests/server/tso_test.(*testLocalTSOSuite).TestLocalTSOAfterMemberChanged()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200702092429-9f69995143ce/failpoints.go:224 +0x6ec
[2021-01-27T08:21:20.432Z]   runtime.call32()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
[2021-01-27T08:21:20.432Z]   reflect.Value.Call()
[2021-01-27T08:21:20.432Z]       /usr/local/go/src/reflect/value.go:321 +0xd3
[2021-01-27T08:21:20.432Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2021-01-27T08:21:20.432Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa
[2021-01-27T08:21:20.433Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-01-27T08:21:20.433Z]       /home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
[2021-01-27T08:21:20.433Z] ==================
[2021-01-27T08:21:20.433Z] panic: runtime error: invalid memory address or nil pointer dereference
[2021-01-27T08:21:20.433Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe9e397]
[2021-01-27T08:21:20.433Z] 
[2021-01-27T08:21:20.433Z] goroutine 157046 [running]:
[2021-01-27T08:21:20.433Z] context.propagateCancel(0x0, 0x0, 0x3e60040, 0xc017ef0540)
[2021-01-27T08:21:20.433Z] 	/usr/local/go/src/context/context.go:242 +0x37
[2021-01-27T08:21:20.433Z] context.WithCancel(0x0, 0x0, 0x14, 0x0, 0x0)
[2021-01-27T08:21:20.433Z] 	/usr/local/go/src/context/context.go:231 +0x10c
[2021-01-27T08:21:20.433Z] google.golang.org/grpc.newClientStream(0x0, 0x0, 0x5020de0, 0xc003243880, 0x32252a7, 0x14, 0xc004e55180, 0x1, 0x1, 0x0, ...)
[2021-01-27T08:21:20.433Z] 	/home/jenkins/agent/workspace/pd_test/go/pkg/mod/google.golang.org/grpc@v1.26.0/stream.go:187 +0x22fb
[2021-01-27T08:21:20.433Z] google.golang.org/grpc.(*ClientConn).NewStream(0xc003243880, 0x0, 0x0, 0x5020de0, 0x32252a7, 0x14, 0x0, 0x0, 0x0, 0xc017f7a9a0, ...)
[2021-01-27T08:21:20.433Z] 	/home/jenkins/agent/workspace/pd_test/go/pkg/mod/google.golang.org/grpc@v1.26.0/stream.go:150 +0x25a
[2021-01-27T08:21:20.433Z] github.com/pingcap/kvproto/pkg/pdpb.(*pDClient).SyncRegions(0xc001087e90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x32, 0x0)
[2021-01-27T08:21:20.433Z] 	/home/jenkins/agent/workspace/pd_test/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20210112051026-540f4cb76c1c/pkg/pdpb/pdpb.pb.go:5157 +0xfe
[2021-01-27T08:21:20.433Z] github.com/tikv/pd/server/region_syncer.(*RegionSyncer).syncRegion(0xc00e027900, 0xc003243880, 0xc017f1f400, 0x3, 0x3, 0x320aa94)
[2021-01-27T08:21:20.433Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/region_syncer/client.go:103 +0xe6
[2021-01-27T08:21:20.433Z] github.com/tikv/pd/server/region_syncer.(*RegionSyncer).StartSyncWithLeader.func1(0xc00e027900, 0xc0060d4f60, 0xc007149ca0, 0x16)
[2021-01-27T08:21:20.433Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/region_syncer/client.go:157 +0x6c6
[2021-01-27T08:21:20.433Z] created by github.com/tikv/pd/server/region_syncer.(*RegionSyncer).StartSyncWithLeader
[2021-01-27T08:21:20.433Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/region_syncer/client.go:125 +0xc3
```
Details can be found in https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/pd_test/detail/pd_test/17961/pipeline

**Comment by duduainankai** [comment]
Seems the `s.regionSyncerCtx` is read without lock. 

May I take this one ?

**Comment by rleungx** [comment]
> Seems the `s.regionSyncerCtx` is read without lock.
> 
> May I take this one ?

Of course

**Comment by Yisaer** [comment]
> Seems the `s.regionSyncerCtx` is read without lock.
> 
> May I take this one ?

Sry I didn't notice this. As this bug have been block my pr, I'v tried to fix it.

**Comment by duduainankai** [comment]
> > Seems the `s.regionSyncerCtx` is read without lock.
> > May I take this one ?
> 
> Sry I didn't notice this. As this bug have been block my pr, I'v tried to fix it.

@Yisaer  It's ok. 

But I have read the pr and I think it's better to do like:

```
s.Lock()
ctx := s.regionSyncerCtx
s.Unlock()
if ctx == nil {
    return nil, status.Error(codes.FailedPrecondition, "region syncer ctx is nil, may have been stopped.")
}
syncStream, err := cli.SyncRegions(ctx)
s.Unlock()
```

**Comment by Yisaer** [comment]
Thanks for your review, you can directly comment on that pr. @duduainankai

**Comment by duduainankai** [comment]
Sure. (xia ci yi ding
