### ISSUE TITLE
pd panic in br integration test

### ISSUE THREAD

**Issue by glorv** [tikv/pd#3746]
### What did you do?
Run br integration test `br_300_small_tables`

### What did you see instead?
pd panic with following back trace:
```
[2021-06-04T06:16:32.882Z] fatal error: concurrent map read and map write
[2021-06-04T06:16:32.882Z] 
[2021-06-04T06:16:32.882Z] goroutine 1954 [running]:
[2021-06-04T06:16:32.882Z] runtime.throw(0x2647d26, 0x21)
[2021-06-04T06:16:32.882Z] 	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc001f47120 sp=0xc001f470f0 pc=0xbbda92
[2021-06-04T06:16:32.882Z] runtime.mapaccess2_fast64(0x2388ac0, 0xc00280f7a0, 0x1, 0xc001ef51e0, 0xb8fb01)
[2021-06-04T06:16:32.882Z] 	/usr/local/go/src/runtime/map_fast64.go:61 +0x1ac fp=0xc001f47148 sp=0xc001f47120 pc=0xb9800c
[2021-06-04T06:16:32.882Z] github.com/tikv/pd/server/statistics.(*hotPeerCache).isRegionHotWithPeer(0xc00246b450, 0xc002fe4f00, 0xc004448d00, 0x3, 0xc002756900)
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/statistics/hot_peer_cache.go:371 +0x57 fp=0xc001f47180 sp=0xc001f47148 pc=0x195c377
[2021-06-04T06:16:32.882Z] github.com/tikv/pd/server/statistics.(*hotPeerCache).isRegionHotWithAnyPeers(0xc00246b450, 0xc002fe4f00, 0x3, 0xf85200)
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/statistics/hot_peer_cache.go:359 +0x91 fp=0xc001f471d0 sp=0xc001f47180 pc=0x195c2d1
[2021-06-04T06:16:32.882Z] github.com/tikv/pd/server/statistics.(*HotCache).IsRegionHot(0xc00242b280, 0xc002fe4f00, 0x3, 0xc0038d7500)
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/statistics/hot_cache.go:175 +0x85 fp=0xc001f47200 sp=0xc001f471d0 pc=0x1957725
[2021-06-04T06:16:32.882Z] github.com/tikv/pd/server/cluster.(*RaftCluster).IsRegionHot(0xc001cf4000, 0xc002fe4f00, 0x0)
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/cluster/cluster.go:925 +0xcf fp=0xc001f47258 sp=0xc001f47200 pc=0x1a0cb0f
[2021-06-04T06:16:32.882Z] github.com/tikv/pd/server/schedulers.(*balanceLeaderScheduler).createOperator(0xc002df42c0, 0xc001f47bb8, 0x0, 0x0, 0x0)
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/schedulers/balance_leader.go:264 +0x58 fp=0xc001f47468 sp=0xc001f47258 pc=0x19d6d98
[2021-06-04T06:16:32.882Z] github.com/tikv/pd/server/schedulers.(*balanceLeaderScheduler).transferLeaderOut(0xc002df42c0, 0xc001f47bb8, 0x0, 0x0, 0x0)
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/schedulers/balance_leader.go:214 +0x748 fp=0xc001f47720 sp=0xc001f47468 pc=0x19d5a08
[2021-06-04T06:16:32.882Z] github.com/tikv/pd/server/schedulers.(*balanceLeaderScheduler).Schedule(0xc002df42c0, 0x2fca038, 0xc001cf4000, 0x0, 0x0, 0x0)
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/schedulers/balance_leader.go:167 +0xf85 fp=0xc001f47c18 sp=0xc001f47720 pc=0x19d4d45
[2021-06-04T06:16:32.882Z] github.com/tikv/pd/server/cluster.(*scheduleController).Schedule(0xc002df6690, 0x2e08301, 0x0, 0x0)
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/cluster/coordinator.go:791 +0x68 fp=0xc001f47c78 sp=0xc001f47c18 pc=0x1a24088
[2021-06-04T06:16:32.882Z] github.com/tikv/pd/server/cluster.(*coordinator).runScheduler(0xc0004ac300, 0xc002df6690)
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/cluster/coordinator.go:742 +0x20c fp=0xc001f47fd0 sp=0xc001f47c78 pc=0x1a2376c
[2021-06-04T06:16:32.882Z] runtime.goexit()
[2021-06-04T06:16:32.882Z] 	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc001f47fd8 sp=0xc001f47fd0 pc=0xbf8ea1
[2021-06-04T06:16:32.882Z] created by github.com/tikv/pd/server/cluster.(*coordinator).addScheduler
[2021-06-04T06:16:32.882Z] 	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/cluster/coordinator.go:600 +0x171
[2021-06-04T06:16:32.882Z] 
```

[Detail log](https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/br_ghpr_unit_and_integration_test/runs/4070/nodes/70/steps/701/log/?start=0)

### What version of PD are you using (`pd-server -V`)?
master branch at commit `6891009b0b7557be2e2e1019d3dc9bfb975d8dfd`

**Comment by rleungx** [comment]
I think it might have already got fixed. Would you like to confirm that once you have the time? @Yisaer

**Comment by nolouch** [comment]
I think fixed in https://github.com/tikv/pd/pull/3721.
