### ISSUE TITLE
ci failed runing too long `TestWatcher`

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4165]
### What did you do?
```
[2021-09-26T10:05:14.356Z] goroutine 1374 [chan receive, 9 minutes]:

[2021-09-26T10:05:14.356Z] github.com/tikv/pd/server/encryptionkm.(*testKeyManagerSuite).TestWatcher(0x29c1450, 0xc0003ca3c0)

[2021-09-26T10:05:14.356Z] 	/home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/encryptionkm/key_manager_test.go:408 +0xb3f

[2021-09-26T10:05:14.356Z] reflect.Value.call(0x1948520, 0x29c1450, 0x4213, 0x199ffed, 0x4, 0xc0000d3ef0, 0x1, 0x1, 0xc00085d508, 0x170455e, ...)

[2021-09-26T10:05:14.356Z] 	/usr/local/go/src/reflect/value.go:476 +0x99c

[2021-09-26T10:05:14.356Z] reflect.Value.Call(0x1948520, 0x29c1450, 0x4213, 0xc00085d6f0, 0x1, 0x1, 0x0, 0x0, 0x0)

[2021-09-26T10:05:14.356Z] 	/usr/local/go/src/reflect/value.go:337 +0xd9

[2021-09-26T10:05:14.356Z] github.com/pingcap/check.(*suiteRunner).forkTest.func1(0xc0003ca3c0)

[2021-09-26T10:05:14.356Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3c

[2021-09-26T10:05:14.356Z] github.com/pingcap/check.(*suiteRunner).forkCall.func1(0xc0002d59e0, 0xc0003ca3c0, 0xc000127840)

[2021-09-26T10:05:14.356Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11e

[2021-09-26T10:05:14.356Z] created by github.com/pingcap/check.(*suiteRunner).forkCall

[2021-09-26T10:05:14.356Z] 	/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4cd
```
details: https://ci2.pingcap.net/blue/organizations/jenkins/pd_test/detail/pd_test/2596/pipeline

### What did you expect to see?
succeed.
### What did you see instead?
failed
### What version of PD are you using (`pd-server -V`)?
master

**Comment by HunDunDM** [comment]
It also happens before #4111 : https://ci2.pingcap.net/blue/organizations/jenkins/pd_test/detail/pd_test/2463/pipeline/51
It seems to be an issue with etcd watcher.

**Comment by HunDunDM** [comment]
At present, it cannot be 100% guaranteed that it has been repaired, and it will be reopened if it is found again in the future.
