### ISSUE TITLE
checkptr: converted pointer straddles multiple allocations

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#4528]
### Which jobs are failing

GitHub Actions & Jenkins/test

### CI link

* https://github.com/tikv/pd/runs/4671500542
* https://ci2.pingcap.net/blue/organizations/jenkins/pd_test/detail/pd_test/4490/pipeline

### Reason for failure (if possible)

```go
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 199 [running]:
runtime.throw(0x295f516, 0x3a)
	/opt/hostedtoolcache/go/1.16.12/x64/src/runtime/panic.go:1117 +0x72 fp=0xc0004c34a0 sp=0xc0004c3470 pc=0xa8b332
runtime.checkptrAlignment(0xc000110550, 0x2806f60, 0x1)
	/opt/hostedtoolcache/go/1.16.12/x64/src/runtime/checkptr.go:20 +0xc9 fp=0xc0004c34d0 sp=0xc0004c34a0 pc=0xa59589
go.etcd.io/bbolt.(*Bucket).write(0xc0004c3670, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/bucket.go:624 +0x265 fp=0xc0004c3568 sp=0xc0004c34d0 pc=0x1ba5ca5
go.etcd.io/bbolt.(*Bucket).CreateBucket(0xc000134018, 0x3c48dfc, 0x7, 0x7, 0xae355f, 0xc0004de908, 0xc0ffffffff)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/bucket.go:181 +0x32d fp=0xc0004c3720 sp=0xc0004c3568 pc=0x1ba1f2d
go.etcd.io/bbolt.(*Tx).CreateBucket(...)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:108
go.etcd.io/etcd/mvcc/backend.(*batchTx).UnsafeCreateBucket(0xc0004d1800, 0x3c48dfc, 0x7, 0x7)
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/mvcc/backend/batch_tx.go:72 +0x9e fp=0xc0004c3960 sp=0xc0004c3720 pc=0x1c0fc9e
go.etcd.io/etcd/mvcc/backend.(*batchTxBuffered).UnsafeCreateBucket(0xc0004d1800, 0x3c48dfc, 0x7, 0x7)
	<autogenerated>:1 +0x65 fp=0xc0004c3990 sp=0xc0004c3960 pc=0x1c1bdc5
go.etcd.io/etcd/etcdserver/api/membership.mustCreateBackendBuckets(0x3266818, 0xc000304480)
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/membership/store.go:166 +0x110 fp=0xc0004c3a28 sp=0xc0004c3990 pc=0x1cbf650
go.etcd.io/etcd/etcdserver/api/membership.(*RaftCluster).SetBackend(...)
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/membership/cluster.go:242
go.etcd.io/etcd/etcdserver.NewServer(0xc00049b5e8, 0x3, 0x0, 0x0, 0x0, 0x0, 0xc000293b00, 0x1, 0x1, 0xc0002938c0, ...)
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/server.go:406 +0x65e5 fp=0xc0004c53c0 sp=0xc0004c3a28 pc=0x1e371e5
go.etcd.io/etcd/embed.StartEtcd(0xc0004ce000, 0xc000101b80, 0x0, 0x0)
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/embed/etcd.go:211 +0x123b fp=0xc0004c74b0 sp=0xc0004c53c0 pc=0x20810fb
github.com/tikv/pd/server.(*Server).startEtcd(0xc00031f860, 0x3254250, 0xc0003aac40, 0x0, 0x0)
	/home/runner/work/pd/pd/server/server.go:276 +0x125 fp=0xc0004c7e90 sp=0xc0004c74b0 pc=0x238a005
github.com/tikv/pd/server.(*Server).Run(0xc00031f860, 0x0, 0x0)
	/home/runner/work/pd/pd/server/server.go:495 +0xf3 fp=0xc0004c7ef0 sp=0xc0004c7e90 pc=0x238ecf3
github.com/tikv/pd/server/api.mustNewCluster.func1(0xc000410000, 0x0, 0x0, 0x0, 0x3254250, 0xc0003aac40, 0xc0003acf60, 0xc00018e600)
	/home/runner/work/pd/pd/server/api/server_test.go:97 +0x285 fp=0xc0004c7fa0 sp=0xc0004c7ef0 pc=0x2519505
runtime.goexit()
	/opt/hostedtoolcache/go/1.16.12/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0004c7fa8 sp=0xc0004c7fa0 pc=0xac7441
created by github.com/tikv/pd/server/api.mustNewCluster
	/home/runner/work/pd/pd/server/api/server_test.go:86 +0x1ee

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000001980, 0x2906c82, 0xd, 0x297b1a8, 0x0)
	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1239 +0x610
testing.runTests.func1(0xc000001980)
	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1511 +0xa7
testing.tRunner(0xc000001980, 0xc00023fb80)
	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1193 +0x203
testing.runTests(0xc0003a1140, 0x3c2e3c0, 0x1, 0x1, 0xc06bbb9f490438cc, 0x8bb748e4e6, 0x3ce4f60, 0xbe7d05)
	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1509 +0x613
testing.(*M).Run(0xc000304b00, 0x0)
	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1417 +0x3b4
go.uber.org/goleak.VerifyTestMain(0x322a2c0, 0xc000304b00, 0x3ce6a60, 0x10, 0x10)
	/home/runner/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x5f
github.com/tikv/pd/server/api.TestMain(...)
	/home/runner/work/pd/pd/server/api/server_test.go:67
main.main()
	_testmain.go:773 +0x3db

goroutine 93 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000330678)
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:173 +0x4bb
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:91 +0x105

goroutine 64 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0002aecf0)
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:173 +0x4bb
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:91 +0x105

goroutine 96 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0003307b0)
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:173 +0x4bb
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:91 +0x105

goroutine 197 [select]:
github.com/pingcap/check.(*resultTracker)._loopRoutine(0xc00034a240)
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:464 +0x185
created by github.com/pingcap/check.(*resultTracker).start
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:444 +0x4d

goroutine 196 [chan receive]:
github.com/pingcap/check.(*suiteRunner).runFunc(...)
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:752
github.com/pingcap/check.(*suiteRunner).runFixture(0xc00034a2d0, 0xc000399ab0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:795 +0xb9
github.com/pingcap/check.(*suiteRunner).run(0xc00034a2d0, 0xc00007ac20)
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:695 +0x12d
github.com/pingcap/check.Run(0x275fba0, 0xc00007ac20, 0xc000077e50, 0xc0000b0630)
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x5b
github.com/pingcap/check.RunAll(0xc0000c3e50, 0x0)
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:113 +0xff7
github.com/pingcap/check.TestingT(0xc000001b00)
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x757
github.com/tikv/pd/server/api.TestAPIServer(0xc000001b00)
	/home/runner/work/pd/pd/server/api/server_test.go:63 +0x50
testing.tRunner(0xc000001b00, 0x297b1a8)
	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1193 +0x203
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.16.12/x64/src/testing/testing.go:1238 +0x5d8

goroutine 198 [chan receive]:
github.com/tikv/pd/server/api.mustNewCluster(0xc000410000, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc000072ab8, 0xa59558, 0xc000072b48, 0xb8e409, ...)
	/home/runner/work/pd/pd/server/api/server_test.go:104 +0x294
github.com/tikv/pd/server/api.mustNewServer(...)
	/home/runner/work/pd/pd/server/api/server_test.go:73
github.com/tikv/pd/server/api.(*testAdminSuite).SetUpSuite(0xc00007ac20, 0xc000410000)
	/home/runner/work/pd/pd/server/api/admin_test.go:39 +0x70
reflect.Value.call(0x275fba0, 0xc00007ac20, 0x213, 0x28fb4f3, 0x4, 0xc000072ef0, 0x1, 0x1, 0xc000060e18, 0x242147e, ...)
	/opt/hostedtoolcache/go/1.16.12/x64/src/reflect/value.go:476 +0x99c
reflect.Value.Call(0x275fba0, 0xc00007ac20, 0x213, 0xc000060ef0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.12/x64/src/reflect/value.go:337 +0xd9
github.com/pingcap/check.(*suiteRunner).runFixture.func1(0xc000410000)
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:799 +0x1d1
github.com/pingcap/check.(*suiteRunner).forkCall.func1(0xc00034a2d0, 0xc000410000, 0x297a988)
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11e
created by github.com/pingcap/check.(*suiteRunner).forkCall
	/home/runner/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4cd

goroutine 201 [select]:
github.com/tikv/pd/pkg/systimemon.StartMonitor(0x3254250, 0xc0003aac40, 0x297d4b0, 0x297b080)
	/home/runner/work/pd/pd/pkg/systimemon/systimemon.go:33 +0x25a
created by github.com/tikv/pd/server.(*Server).Run
	/home/runner/work/pd/pd/server/server.go:491 +0xac

goroutine 203 [select]:
go.etcd.io/etcd/mvcc/backend.(*backend).run(0xc000304480)
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/mvcc/backend/backend.go:323 +0x225
created by go.etcd.io/etcd/mvcc/backend.newBackend
	/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/mvcc/backend/backend.go:185 +0x7e5
FAIL	github.com/tikv/pd/server/api	0.165s
```

**Comment by JmPotato** [comment]
Seems related: https://github.com/hashicorp/raft-boltdb/issues/21
