### ISSUE TITLE
all pds panic after scale out pd

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#4814]
### What did you do?
https://tcms.pingcap.net/dashboard/executions/plan/781242
scale out pd from 3 to 4

### What did you expect to see?
all pds are normal

### What did you see instead?
after scale out，all pds panic
![image](https://user-images.githubusercontent.com/84712107/163752904-60a145d5-d3cb-41b1-bc0a-54f6a19e8ab2.png)

"panic: runtime error: invalid memory address or nil pointer dereference\n"
![image](https://user-images.githubusercontent.com/84712107/163752133-6adb9358-eb6b-42da-95b7-e8f14b33958a.png)
2022-04-17 21:30:06	log="starting pd-server ...\n"
2022-04-17 21:30:06	log="nslookup domain tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc.svc success\n"
2022-04-17 21:30:06	log="\n"
2022-04-17 21:30:06	log="Address: 10.233.79.11\n"
2022-04-17 21:30:06	log="Name:\ttc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc.cluster.local\n"
2022-04-17 21:30:06	log="\n"
2022-04-17 21:30:06	log="Address:\t10.96.0.10#53\n"
2022-04-17 21:30:06	log="Server:\t\t10.96.0.10\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xea\n"
2022-04-17 21:29:50	log="created by google.golang.org/grpc.(*Server).serveStreams.func1\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0x98\n"
2022-04-17 21:29:50	log="google.golang.org/grpc.(*Server).serveStreams.func1.1()\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1317 +0x9be\n"
2022-04-17 21:29:50	log="google.golang.org/grpc.(*Server).handleStream(0xc0018fa300, {0x33cac10, 0xc0030d7380}, 0xc003052a00, 0x0)\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1244 +0xd66\n"
2022-04-17 21:29:50	log="google.golang.org/grpc.(*Server).processStreamingRPC(0xc0018fa300, {0x33cac10, 0xc0030d7380}, 0xc003052a00, 0xc006173b90, 0x432afe0, 0x0)\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:79 +0x1a3\n"
2022-04-17 21:29:50	log="github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1({0x2711a00, 0xc005774060}, {0x33c7280, 0xc001a01440}, 0xc0033459e0, 0x30d4778)\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/v3rpc/interceptor.go:225 +0x383\n"
2022-04-17 21:29:50	log="go.etcd.io/etcd/etcdserver/api/v3rpc.newStreamInterceptor.func1({0x2711a00, 0xc005774060}, {0x33c7280?, 0xc001a01440?}, 0xc0033459e0?, 0xc005492370)\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:74 +0x6f\n"
2022-04-17 21:29:50	log="github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1({0x2711a00?, 0xc005774060?}, {0x33c7280?, 0xc001a01440?})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121 +0x109\n"
2022-04-17 21:29:50	log="github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1({0x2711a00, 0xc005774060}, {0x33c7280?, 0xc001a01440}, 0x24aaf80?, 0xc005492370)\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:71 +0x89\n"
2022-04-17 21:29:50	log="github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1({0x2711a00?, 0xc005774060?}, {0x33c67d0?, 0xc0033459f8?})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/pdpb/pdpb.pb.go:7564 +0xa2\n"
2022-04-17 21:29:50	log="github.com/pingcap/kvproto/pkg/pdpb._PD_SyncRegions_Handler({0x2711a00?, 0xc005774060}, {0x33c67d0?, 0xc0033459f8})\n"
2022-04-17 21:29:50	log="\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/grpc_service.go:1326 +0xa8\n"
2022-04-17 21:29:50	log="github.com/tikv/pd/server.(*GrpcServer).SyncRegions(0xc005774060, {0x33c8fd8, 0xc0056cf7a0})\n"
2022-04-17 21:29:50	log="\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/region_syncer/server.go:207 +0x385\n"
2022-04-17 21:29:50	log="github.com/tikv/pd/server/region_syncer.(*RegionSyncer).Sync(0xc0004ee620, {0x33bf758, 0xc0064ed500}, {0x33c8fd8?, 0xc0056cf7a0})\n"
2022-04-17 21:29:50	log="\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/region_syncer/server.go:313 +0x16e4\n"
2022-04-17 21:29:50	log="github.com/tikv/pd/server/region_syncer.(*RegionSyncer).syncHistoryRegion(0xc0004ee620, {0x33bf758, 0xc0064ed500}, 0x2?, {0x33c8fd8, 0xc0056cf7a0})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/pdpb/pdpb.pb.go:7578 +0x2b\n"
2022-04-17 21:29:50	log="github.com/pingcap/kvproto/pkg/pdpb.(*pDSyncRegionsServer).Send(0x2769312?, 0x24?)\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:156 +0x33\n"
2022-04-17 21:29:50	log="github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredServerStream).SendMsg(0xc0033459f8, {0x26a6ba0?, 0xc001aa2630?})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/google.golang.org/grpc@v1.26.0/stream.go:1412 +0xf3\n"
2022-04-17 21:29:50	log="google.golang.org/grpc.(*serverStream).SendMsg(0xc001a01440, {0x26a6ba0?, 0xc001aa2630})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/google.golang.org/grpc@v1.26.0/stream.go:1519 +0xd2\n"
2022-04-17 21:29:50	log="google.golang.org/grpc.prepareMsg({0x26a6ba0?, 0xc001aa2630?}, {0x7f890014b870?, 0x4d2c7e8?}, {0x0, 0x0}, {0x0, 0x0})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/google.golang.org/grpc@v1.26.0/rpc_util.go:543 +0x44\n"
2022-04-17 21:29:50	log="google.golang.org/grpc.encode({0x7f890014b870?, 0x4d2c7e8?}, {0x26a6ba0?, 0xc001aa2630?})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/v3rpc/codec.go:22 +0x38\n"
2022-04-17 21:29:50	log="go.etcd.io/etcd/etcdserver/api/v3rpc.(*codec).Marshal(0xc0060d9088?, {0x26a6ba0?, 0xc001aa2630})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/table_marshal.go:2940 +0x144\n"
2022-04-17 21:29:50	log="github.com/gogo/protobuf/proto.Marshal({0x7f89001635f8, 0xc001aa2630})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/pdpb/pdpb.pb.go:5013 +0x37\n"
2022-04-17 21:29:50	log="github.com/pingcap/kvproto/pkg/pdpb.(*SyncRegionResponse).XXX_Marshal(0x7f89001635f8?, {0xc002d1b000, 0xc001aa2630?, 0xe19}, 0x45?)\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/pdpb/pdpb.pb.go:12213 +0x6e5\n"
2022-04-17 21:29:50	log="github.com/pingcap/kvproto/pkg/pdpb.(*SyncRegionResponse).MarshalToSizedBuffer(0xc001aa2630, {0xc002d1b000, 0xe19, 0xe19})\n"
2022-04-17 21:29:50	log="\t/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/metapb/metapb.pb.go:1240 +0x2c\n"
2022-04-17 21:29:50	log="github.com/pingcap/kvproto/pkg/metapb.(*Buckets).MarshalToSizedBuffer(0x0, {0xc002d1b000, 0xe19, 0xe19})\n"
2022-04-17 21:29:50	log="goroutine 19182 [running]:\n"
2022-04-17 21:29:50	log="\n"
2022-04-17 21:29:50	log="[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x11f580c]\n"
2022-04-17 21:29:50	log="panic: runtime error: invalid memory address or nil pointer dereference\n"
2022-04-17 21:29:49	log="[2022/04/17 13:29:49.919 +00:00] [WARN] [retry_interceptor.go:61] [\"retrying of unary invoker failed\"] [target=endpoint://client-7f2c86f5-020d-4057-b3bd-a2ec5e26ae8d/tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc:2379] [attempt=0] [error=\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"]\n"
2022-04-17 21:29:47	log="[2022/04/17 13:29:47.056 +00:00] [WARN] [retry_interceptor.go:61] [\"retrying of unary invoker failed\"] [target=endpoint://client-7f2c86f5-020d-4057-b3bd-a2ec5e26ae8d/tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc:2379] [attempt=0] [error=\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"]\n"
2022-04-17 21:29:45	log="[2022/04/17 13:29:45.932 +00:00] [WARN] [retry_interceptor.go:61] [\"retrying of unary invoker failed\"] [target=endpoint://client-dac790cb-8c80-4cb6-a915-e74bb51ae12e/tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc:2379] [attempt=0] [error=\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"]\n"
2022-04-17 21:29:45	log="[2022/04/17 13:29:45.025 +00:00] [WARN] [retry_interceptor.go:61] [\"retrying of unary invoker failed\"] [target=endpoint://client-dac790cb-8c80-4cb6-a915-e74bb51ae12e/tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc:2379] [attempt=1] [error=\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"]\n"
2022-04-17 21:29:44	log="[2022/04/17 13:29:44.491 +00:00] [WARN] [retry_interceptor.go:61] [\"retrying of unary invoker failed\"] [target=endpoint://client-7f2c86f5-020d-4057-b3bd-a2ec5e26ae8d/tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc:2379] [attempt=0] [error=\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"]\n"
2022-04-17 21:29:41	log="[2022/04/17 13:29:41.948 +00:00] [WARN] [retry_interceptor.go:61] [\"retrying of unary invoker failed\"] [target=endpoint://client-7f2c86f5-020d-4057-b3bd-a2ec5e26ae8d/tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc:2379] [attempt=0] [error=\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"]\n"
2022-04-17 21:29:39	log="[2022/04/17 13:29:39.312 +00:00] [WARN] [retry_interceptor.go:61] [\"retrying of unary invoker failed\"] [target=endpoint://client-dac790cb-8c80-4cb6-a915-e74bb51ae12e/tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc:2379] [attempt=0] [error=\"rpc error: code = Unavailable desc = etcdserver: leader changed\"]\n"
2022-04-17 21:29:22	log="/pd-server --data-dir=/var/lib/pd/data --name=tc-pd-0 --peer-urls=http://0.0.0.0:2380 --advertise-peer-urls=http://tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc:2380 --client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://tc-pd-0.tc-pd-peer.endless-oltp-tps-781242-1-748.svc:2379 --config=/etc/pd/pd.toml \n"

http://172.16.4.67:30698/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22test-infra-prod-Loki%22,%7B%22expr%22:%22%7Bpod%3D%5C%22tc-pd-0%5C%22,testbed%3D%5C%22endless-oltp-tps-781242-1-748%5C%22%7D%20!%3D%20%5C%22level%5C%22%22%7D%5D

### What version of PD are you using (`pd-server -V`)?
./tikv-server -V
 TiKV 
Release Version:   6.0.0-alpha
Edition:           Community
Git Commit Hash:   45fcb0812a0437cabce2436c5223c96c9de83d5e
Git Commit Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:    2022-04-15 11:00:36
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
./pd-server -V
 Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: b7c32969997de7681915967449126b028e18aa67
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:  2022-04-15 10:58:09
./tidb-server -V
 Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: ecb0c98d3332119b5f00b262cd213201fcf1f1b0
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-04-15 23:03:44
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
./br -V
 Release Version: v6.1.0-nightly
Git Commit Hash: ecb0c98d3332119b5f00b262cd213201fcf1f1b0
Git Branch: heads/refs/tags/v6.1.0-nightly
Go Version: go1.18
UTC Build Time: 2022-04-15 22:57:11

**Comment by JmPotato** [comment]
After https://github.com/tikv/pd/pull/4750 is merged, the `RegionSyncer` will sync the history regions' buckets with the newly added server. However, since the buckets could be `nil` here, it will cause panic when trying to marshal a slice with a `nil` element.

https://github.com/tikv/pd/blob/b7c32969997de7681915967449126b028e18aa67/server/region_syncer/server.go#L294-L313

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x10490406c]

goroutine 1267 [running]:
github.com/pingcap/kvproto/pkg/metapb.(*Buckets).MarshalToSizedBuffer(0x0, {0x1400033c420, 0x149, 0x149})
	/Users/jmpotato/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/metapb/metapb.pb.go:1240 +0x2c
github.com/pingcap/kvproto/pkg/pdpb.(*SyncRegionResponse).MarshalToSizedBuffer(0x140017530e0, {0x1400033c420, 0x149, 0x149})
	/Users/jmpotato/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/pdpb/pdpb.pb.go:12213 +0x684
github.com/pingcap/kvproto/pkg/pdpb.(*SyncRegionResponse).XXX_Marshal(0x1400258cf48?, {0x1400033c420, 0x140017530e0?, 0x149}, 0x0?)
	/Users/jmpotato/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/pdpb/pdpb.pb.go:5013 +0x34
github.com/gogo/protobuf/proto.Marshal({0x10f201810, 0x140017530e0})
	/Users/jmpotato/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/table_marshal.go:2940 +0x150
go.etcd.io/etcd/etcdserver/api/v3rpc.(*codec).Marshal(0x1400258d018?, {0x10693d540?, 0x140017530e0})
	/Users/jmpotato/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/v3rpc/codec.go:22 +0x38
google.golang.org/grpc.encode({0x10f135ec0?, 0x10775d900?}, {0x10693d540?, 0x140017530e0?})
	/Users/jmpotato/go/pkg/mod/google.golang.org/grpc@v1.26.0/rpc_util.go:543 +0x44
google.golang.org/grpc.prepareMsg({0x10693d540?, 0x140017530e0?}, {0x10f135ec0?, 0x10775d900?}, {0x0, 0x0}, {0x0, 0x0})
	/Users/jmpotato/go/pkg/mod/google.golang.org/grpc@v1.26.0/stream.go:1519 +0xb4
google.golang.org/grpc.(*serverStream).SendMsg(0x14000f52540, {0x10693d540?, 0x140017530e0})
	/Users/jmpotato/go/pkg/mod/google.golang.org/grpc@v1.26.0/stream.go:1412 +0xa4
github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredServerStream).SendMsg(0x14000111278, {0x10693d540?, 0x140017530e0?})
	/Users/jmpotato/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:156 +0x3c
github.com/pingcap/kvproto/pkg/pdpb.(*pDSyncRegionsServer).Send(0x10595db94?, 0x24?)
	/Users/jmpotato/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/pdpb/pdpb.pb.go:7578 +0x38
github.com/tikv/pd/server/region_syncer.(*RegionSyncer).syncHistoryRegion(0x14000515f10, {0x1069d0710, 0x140042eb1c0}, 0x2?, {0x1069d9700, 0x140015c56c0})
	/Users/jmpotato/go/src/github.com/JmPotato/pd/server/region_syncer/server.go:313 +0x12b0
github.com/tikv/pd/server/region_syncer.(*RegionSyncer).Sync(0x14000515f10, {0x1069d0710, 0x140042eb1c0}, {0x1069d9700?, 0x140015c56c0})
	/Users/jmpotato/go/src/github.com/JmPotato/pd/server/region_syncer/server.go:207 +0x2d8
github.com/tikv/pd/server.(*GrpcServer).SyncRegions(0x1400030a448, {0x1069d9700, 0x140015c56c0})
	/Users/jmpotato/go/src/github.com/JmPotato/pd/server/grpc_service.go:1326 +0xa4
github.com/pingcap/kvproto/pkg/pdpb._PD_SyncRegions_Handler({0x1069a7b60?, 0x1400030a448}, {0x1069d6ff0?, 0x14000111278})
	/Users/jmpotato/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220330070404-8c4cd3f93748/pkg/pdpb/pdpb.pb.go:7564 +0xa0
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1({0x1069a7b60?, 0x1400030a448?}, {0x1069d6ff0?, 0x14000111278?})
	/Users/jmpotato/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:71 +0xa0
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1({0x1069a7b60, 0x1400030a448}, {0x1069d7a10?, 0x14000f52540}, 0x10674be00?, 0x140017a9db0)
	/Users/jmpotato/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121 +0x110
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1({0x1069a7b60?, 0x1400030a448?}, {0x1069d7a10?, 0x14000f52540?})
	/Users/jmpotato/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:74 +0x78
go.etcd.io/etcd/etcdserver/api/v3rpc.newStreamInterceptor.func1({0x1069a7b60, 0x1400030a448}, {0x1069d7a10?, 0x14000f52540?}, 0x0?, 0x140017a9db0)
	/Users/jmpotato/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/v3rpc/interceptor.go:225 +0x370
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1({0x1069a7b60, 0x1400030a448}, {0x1069d7a10, 0x14000f52540}, 0x14000111260, 0x1069aff58)
	/Users/jmpotato/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:79 +0x17c
google.golang.org/grpc.(*Server).processStreamingRPC(0x1400026c000, {0x1069db398, 0x1400457f680}, 0x14001033800, 0x140017a0fc0, 0x1076d4560, 0x0)
	/Users/jmpotato/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1244 +0xc24
google.golang.org/grpc.(*Server).handleStream(0x1400026c000, {0x1069db398, 0x1400457f680}, 0x14001033800, 0x0)
	/Users/jmpotato/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1317 +0x874
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/Users/jmpotato/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/jmpotato/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xec
```

cc @bufferflies
