### ISSUE TITLE
pd crashed during unsafe remove-failed-stores

### ISSUE THREAD

**Issue by hihihuhu** [tikv/pd#5418]
### What did you do?

when execute pd-ctl unsafe remove-failed-stores, the pd crashes with

```
[2022/08/10 16:32:01.142 +00:00] [INFO] [unsafe_recovery_controller.go:505] ["{\"info\":\"Unsafe recovery enters exit force leader stage\",\"time\":\"2022-08-10 16:32:01.142\",\"details\":[\"triggered by error: region \\u0026{0xc06ac4c980 14048}'s epoch shouldn't be staler than old ones \\u0026{0xc0658f71c0 14039}\"]}"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b599d4]

goroutine 834457685 [running]:
github.com/tikv/pd/server/cluster.(*unsafeRecoveryController).generateExitForceLeaderPlan(...)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/cluster/unsafe_recovery_controller.go:1154
github.com/tikv/pd/server/cluster.(*unsafeRecoveryController).HandleStoreHeartbeat(0xc01e88bce0, 0x1?, 0x0?)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/cluster/unsafe_recovery_controller.go:343 +0x514
github.com/tikv/pd/server.(*GrpcServer).StoreHeartbeat(0xc009d9d760, {0x33acbc0?, 0xc0b8efbad0?}, 0xc0b8eff000)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/grpc_service.go:624 +0x5c5
github.com/pingcap/kvproto/pkg/pdpb._PD_StoreHeartbeat_Handler.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00?, 0xc0b8eff000})
        /go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220510035547-0e2f26c0a46a/pkg/pdpb/pdpb.pb.go:7467 +0x7b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1({0x33acbc0?, 0xc0b8efbad0?}, {0x2685c00?, 0xc0b8eff000?})
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31 +0x89
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00, 0xc0b8eff000}, 0x24ac200?, 0xc0358f6f00)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1({0x33acbc0?, 0xc0b8efbad0?}, {0x2685c00?, 0xc0b8eff000?})
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x6f
go.etcd.io/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00?, 0xc0b8eff000}, 0x0?, 0xc0358f6f00)
        /go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/v3rpc/interceptor.go:64 +0x1b6
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1({0x33acbc0?, 0xc0b8efbad0?}, {0x2685c00?, 0xc0b8eff000?})
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x6f
go.etcd.io/etcd/etcdserver/api/v3rpc.newLogUnaryInterceptor.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00, 0xc0b8eff000}, 0xc0bcf2a140, 0xc0358f6f00)
        /go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/api/v3rpc/interceptor.go:71 +0xc3
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x33acbc0, 0xc0b8efbad0}, {0x2685c00, 0xc0b8eff000}, 0xc0bcf2a140, 0xc050ccfae8)
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39 +0x1a3
github.com/pingcap/kvproto/pkg/pdpb._PD_StoreHeartbeat_Handler({0x2700f60?, 0xc009d9d760}, {0x33acbc0, 0xc0b8efbad0}, 0xc08afe4720, 0xc001f8d350)
        /go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20220510035547-0e2f26c0a46a/pkg/pdpb/pdpb.pb.go:7469 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00067e480, {0x33b7950, 0xc0676b1b90}, 0xc028e50c00, 0xc000907d10, 0x433d028, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc00067e480, {0x33b7950, 0xc0676b1b90}, 0xc028e50c00, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xa05
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xea
```
however, retry the command could succeed

### What did you expect to see?

the command doesn't crash pd, either succeed or fail gracefully with meaningful error message

### What did you see instead?

pd crashed

### What version of PD are you using (`pd-server -V`)?
v6.1.0

**Comment by Connor1996** [comment]
PTAL @v01dstar
