### ISSUE TITLE
Run PD on docker error : ["tocommit(1556396) is out of range [lastIndex(3)].

### ISSUE THREAD

**Issue by Jayuda** [tikv/pd#5588]
## Bug Report
i start a container docker with command : 
```
docker run -d --name pd1 \
-p 2379:2379 \
-p 2380:2380 \
-v /etc/localtime:/etc/localtime:ro \
-v /home/SDB/TIKV/pd1_data:/data \
--restart=always \
--cpus="10" \
--memory="20g" \
--log-opt max-file=1 \
--log-opt max-size=1m \
pingcap/pd:v6.2.0 \
--name="pd1" \
--data-dir="/data/pd1" \
--client-urls="http://0.0.0.0:2379" \
--advertise-client-urls="http://10.10.0.185:2379" \
--peer-urls="http://0.0.0.0:2380" \
--advertise-peer-urls="http://10.10.0.185:2380" \
--initial-cluster="pd1=http://10.10.0.185:2380,pd2=http://10.10.0.208:2380,pd3=http://10.10.0.24:2380"

```
### What did you do?
Docker wont running with error : 
```
[2022/10/12 04:54:06.453 +00:00] [INFO] [stream.go:250] ["set message encoder"] [from=99370ec515c8706d] [to=99370ec515c8706d] [stream-type="stream MsgApp v2"]
[2022/10/12 04:54:06.453 +00:00] [INFO] [peer_status.go:51] ["peer became active"] [peer-id=110fb238e76d467d]
[2022/10/12 04:54:06.453 +00:00] [WARN] [stream.go:277] ["established TCP streaming connection with remote peer"] [stream-writer-type="stream MsgApp v2"] [local-member-id=99370ec515c8706d] [remote-peer-id=110fb238e76d467d]
[2022/10/12 04:54:06.487 +00:00] [INFO] [server.go:716] ["initialized peer connections; fast-forwarding election ticks"] [local-member-id=99370ec515c8706d] [forward-ticks=4] [forward-duration=2s] [election-ticks=6] [election-timeout=3s] [active-remote-members=2]
[2022/10/12 04:54:06.534 +00:00] [INFO] [raft.go:859] ["99370ec515c8706d [term: 1] received a MsgHeartbeat message with higher term from 110fb238e76d467d [term: 10]"]
[2022/10/12 04:54:06.534 +00:00] [INFO] [raft.go:700] ["99370ec515c8706d became follower at term 10"]
[2022/10/12 04:54:06.534 +00:00] [PANIC] [log.go:203] ["tocommit(1556396) is out of range [lastIndex(3)]. Was the raft log corrupted, truncated, or lost?"]
panic: tocommit(1556396) is out of range [lastIndex(3)]. Was the raft log corrupted, truncated, or lost?

goroutine 307 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0017800c0, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*SugaredLogger).log(0xc0000102c8, 0x4, {0x2963d11?, 0xd4dec5?}, {0xc001a92080?, 0x2571c40?, 0xe28e00?}, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/pkg/mod/go.uber.org/zap@v1.19.1/sugar.go:159
go.etcd.io/etcd/pkg/logutil.(*zapRaftLogger).Panicf(0x17bfac?, {0x2963d11?, 0xc0001b2060?}, {0xc001a92080?, 0xe2c8e4?, 0xc0001b2060?})
	/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220712081845-4636a5fab43f/pkg/logutil/zap_raft.go:101 +0x49
go.etcd.io/etcd/raft.(*raftLog).commitTo(0xc0009003f0, 0x17bfac)
	/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220712081845-4636a5fab43f/raft/log.go:203 +0xfe
go.etcd.io/etcd/raft.(*raft).handleHeartbeat(_, {0x8, 0x99370ec515c8706d, 0x110fb238e76d467d, 0xa, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
	/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220712081845-4636a5fab43f/raft/raft.go:1396 +0x45
go.etcd.io/etcd/raft.stepFollower(_, {0x8, 0x99370ec515c8706d, 0x110fb238e76d467d, 0xa, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
	/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220712081845-4636a5fab43f/raft/raft.go:1341 +0x385
go.etcd.io/etcd/raft.(*raft).Step(_, {0x8, 0x99370ec515c8706d, 0x110fb238e76d467d, 0xa, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
	/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220712081845-4636a5fab43f/raft/raft.go:984 +0xfdd
go.etcd.io/etcd/raft.(*node).run(0xc0002810e0)
	/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220712081845-4636a5fab43f/raft/node.go:352 +0xb25
created by go.etcd.io/etcd/raft.RestartNode
	/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220712081845-4636a5fab43f/raft/node.go:240 +0x24a

```
### What did you expect to see?
Running container

### What version of PD are you using (`pd-server -V`)?
v6.2.0

**Comment by rleungx** [comment]
Do you start a new cluster or an existing cluster? if it's the latter one, does the local data still exist?

**Comment by Jayuda** [comment]
Actually i want to replace broken node from pd cluster. I Was create new issue with detail information here 
https://github.com/tikv/pd/issues/5593

So I closed this issue to refer issues 5593
Thanks
