### ISSUE TITLE
PD crashes with "index out of range [-1]"

### ISSUE THREAD

**Issue by guoshouyan** [tikv/pd#6045]
## Bug Report

We noticed there's a latency spike in out tidb cluster, then we found out the PD leader crashed during the latency spike. 
The error log shows
```
[2023/02/23 13:47:15.126 +00:00] [INFO] [operator_controller.go:652] ["send schedule command"] [region-id=2021726092] [step="add learner peer 2022486223 on store 14039"] [source=heartbeat]
panic: runtime error: index out of range [-1]

goroutine 490607653 [running]:
github.com/pingcap/kvproto/pkg/pdpb.(*GetStoreResponse).MarshalToSizedBuffer(0xc0b753fd40, {0xc073e36000, 0x75f2, 0x75f2})
/go/pkg/mod/github.com/pingcap/[kvproto@v0.0.0-20220510035547-0e2f26c0a46a](mailto:kvproto@v0.0.0-20220510035547-0e2f26c0a46a)/pkg/pdpb/pdpb.pb.go:9059 +0x28d
github.com/pingcap/kvproto/pkg/pdpb.(*GetStoreResponse).XXX_Marshal(0xc09586b0e0?, {0xc073e36000, 0xc0b753fd40?, 0x75f2}, 0xf0?)
/go/pkg/mod/github.com/pingcap/[kvproto@v0.0.0-20220510035547-0e2f26c0a46a](mailto:kvproto@v0.0.0-20220510035547-0e2f26c0a46a)/pkg/pdpb/pdpb.pb.go:1291 +0x37
github.com/gogo/protobuf/proto.Marshal({0x7f6339f43178, 0xc0b753fd40})
/go/pkg/mod/github.com/gogo/[protobuf@v1.3.2](mailto:protobuf@v1.3.2)/proto/table_marshal.go:2940 +0x144
go.etcd.io/etcd/etcdserver/api/v3rpc.(*codec).Marshal(0x267dba0?, {0x267dba0?, 0xc0b753fd40})
/go/pkg/mod/go.etcd.io/[etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738](mailto:etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738)/etcdserver/api/v3rpc/codec.go:22 +0x38
google.golang.org/grpc.encode({0x7f661c092c18?, 0x444ece8?}, {0x267dba0?, 0xc0b753fd40?})
/go/pkg/mod/google.golang.org/[grpc@v1.26.0](mailto:grpc@v1.26.0)/rpc_util.go:543 +0x44
google.golang.org/grpc.(*Server).sendResponse(0xc001511b00, {0x33b7950, 0xc055e28480}, 0xc06d96db00, {0x267dba0?, 0xc0b753fd40}, {0x0, 0x0}, 0x17530cf?, {0x0, ...})
/go/pkg/mod/google.golang.org/[grpc@v1.26.0](mailto:grpc@v1.26.0)/server.go:845 +0x1b1
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001511b00, {0x33b7950, 0xc055e28480}, 0xc06d96db00, 0xc008854450, 0x433cfe0, 0x0)
/go/pkg/mod/google.golang.org/[grpc@v1.26.0](mailto:grpc@v1.26.0)/server.go:1059 +0xde5
google.golang.org/grpc.(*Server).handleStream(0xc001511b00, {0x33b7950, 0xc055e28480}, 0xc06d96db00, 0x0)
/go/pkg/mod/google.golang.org/[grpc@v1.26.0](mailto:grpc@v1.26.0)/server.go:1313 +0xa05
google.golang.org/grpc.(*Server).serveStreams.func1.1()
/go/pkg/mod/google.golang.org/[grpc@v1.26.0](mailto:grpc@v1.26.0)/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
/go/pkg/mod/google.golang.org/[grpc@v1.26.0](mailto:grpc@v1.26.0)/server.go:720 +0xea
```

### What did you do?

pd leader switch to another pod and the latency spike disappear

### What did you expect to see?
pd not crashed with the above error

### What version of PD are you using (`pd-server -V`)?
Release Version: v6.1.0
Edition: Community
Git Commit Hash: d82f4fab6cf37cd1eca9c3574984e12a7ae27c42
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time:  2022-06-01 01:44:08

**Comment by glorv** [comment]
seems the same issue as https://github.com/tikv/pd/pull/5374

**Comment by glorv** [comment]
@nolouch Do you have any ideas about this issue? The pb message's serialization code is generated, it's unlikely that there are any known bugs. And I go through the code related code about this, and didn't find any code path that can cause a data race either.

**Comment by bufferflies** [comment]
> proto.Marshal

I notice one reference can edit this [rawstats](https://github.com/tikv/pd/blob/45d7867323fc25a3b0d311cdbc2efed29730d0f2/server/core/store_stats.go#L48)

**Comment by glorv** [comment]
> > proto.Marshal
> 
> I notice one reference can edit this [rawstats](https://github.com/tikv/pd/blob/45d7867323fc25a3b0d311cdbc2efed29730d0f2/server/core/store_stats.go#L48)

But this function is only called on cloned store object.

**Comment by bufferflies** [comment]
I find one suspected code: 
https://github.com/tikv/pd/blob/656f50d4578c50e8aa658459cc866a68c12ba6c2/server/core/store.go#L562-L581
My test code:
```
func Test_Marsh(t *testing.T) {
	re := require.New(t)
	id := uint64(0)
	storeStats := &pdpb.StoreStats{
		DamagedRegionsId: []uint64{1, 2, 3, 4},
	}
	labels := make([]*metapb.StoreLabel, 0, 0)

	for i := 0; i < 11; i++ {
		ll := &metapb.StoreLabel{
			Key:   "2",
			Value: "1",
		}
		labels = append(labels, ll)
	}

	meta := &metapb.Store{
		Labels: labels,
	}
	resp := pdpb.GetStoreResponse{
		Header: &pdpb.ResponseHeader{
			ClusterId: id,
		},
		Store: meta,
		Stats: storeStats,
	}

	size := resp.Size()
	dAtA := make([]byte, size)
	go func() {
		id = 1000
		storeStats = &pdpb.StoreStats{
			DamagedRegionsId: []uint64{1, 2, 3, 4, 5, 6},
		}
		labels := resp.Store.Labels[:0]
		labels = append(labels, &metapb.StoreLabel{Key: "5", Value: "611111"})
	}()

	time.Sleep(time.Second * 1)
	resp.Marshal()
	_, err := resp.MarshalToSizedBuffer(dAtA[:size])
	re.Nil(err)
}
```
the panic stack:
```
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/23159587/222409060-b1f9e919-bd99-4c24-80c1-9f3ad967c5a6.png">

```
