### ISSUE TITLE
PD maybe panic after scatter

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#6126]
### What did you do?
import some data.

### What did you expect to see?
work well

### What did you see instead?
panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e36ed8]

goroutine 3556 [running]:
github.com/tikv/pd/server/schedule.allowLeader(0x2958800?, 0xc00262c1e0?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/schedule/region_scatterer.go:410 +0x58
github.com/tikv/pd/server/schedule.(*RegionScatterer).scatterRegion.func1(0x2956e20?, {{0xc00185ca70, 0x2, 0x2}, 0xc0005f8aa0, 0xc0005f8ac0})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/schedule/region_scatterer.go:348 +0x40e
github.com/tikv/pd/server/schedule.(*RegionScatterer).scatterRegion(0xc00087c680, 0xc0023e0700, {0x0, 0x0})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/schedule/region_scatterer.go:357 +0x6db
github.com/tikv/pd/server/schedule.(*RegionScatterer).Scatter(0xc00087c680, 0xc0023e0700, {0x0, 0x0})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/schedule/region_scatterer.go:301 +0x228
github.com/tikv/pd/server.(*GrpcServer).ScatterRegion(0xc0015080d0, {0x39e53f8?, 0xc00262c0f0?}, 0xc0006679d0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/grpc_service.go:1336 +0x365
github.com/pingcap/kvproto/pkg/pdpb._PD_ScatterRegion_Handler.func1({0x39e53f8, 0xc00262c0f0}, {0x2baa840?, 0xc0006679d0})
	
```

the root cause：https://github.com/tikv/pd/blob/c40e319f50822678cda71ae62ee2fd70a9cac010/server/schedule/region_scatterer.go#L410-L413

the peer maybe not in the rule.

### What version of PD are you using (`pd-server -V`)?
master

**Comment by bufferflies** [comment]
ref https://github.com/tikv/pd/issues/6099

**Comment by nolouch** [comment]
ref https://github.com/tikv/pd/issues/6099.
