### ISSUE TITLE
Panic due to the nil PD/TSO client

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#6159]
## Bug Report

Ref https://github.com/tikv/client-go/actions/runs/4403635107/jobs/7712245145.

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xcce915]

goroutine 5994 [running]:
github.com/tikv/pd/client.(*client).GetRegion(0xc000cda000, {0x20df860, 0xc0020a3740}, {0xc000c9a0a0, 0x9, 0x9}, {0xc000c9e2e8, 0x1, 0x493301?})
	/home/runner/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20230313083840-3e3ae55f68ac/client.go:596 +0x3b5
github.com/tikv/client-go/v2/internal/locate.(*CodecPDClient).GetRegion(0xc000645860, {0x20df860, 0xc0020a3740}, {0xc0020b013a?, 0x1e61540?, 0x40f7ff?}, {0xc000c9e2e8, 0x1, 0x1})
	/home/runner/work/client-go/client-go/internal/locate/pd_codec.go:97 +0xa8
github.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadRegion(0xc000fd8e00, 0xc0007ed050, {0xc0020b013a, 0x2, 0x2}, 0x0)
	/home/runner/work/client-go/client-go/internal/locate/region_cache.go:1502 +0x388
github.com/tikv/client-go/v2/internal/locate.(*RegionCache).findRegionByKey(0xc000fd8e00, 0xc0007ed050, {0xc0020b013a, 0x2, 0x2}, 0xc0?)
	/home/runner/work/client-go/client-go/internal/locate/region_cache.go:986 +0x425
github.com/tikv/client-go/v2/internal/locate.(*RegionCache).LocateKey(0x19?, 0x0?, {0xc0020b013a?, 0x0?, 0x1b025c0?})
	/home/runner/work/client-go/client-go/internal/locate/region_cache.go:941 +0x36
github.com/tikv/client-go/v2/txnkv/transaction.groupSortedMutationsByRegion(0x0?, 0x0?, {0x20f2740, 0xc0020c1080})
	/home/runner/work/client-go/client-go/txnkv/transaction/2pc.go:825 +0x2d0
github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).groupMutations(0xc00056d340, 0xc0007ed050, {0x20f2740, 0xc0020c1080})
	/home/runner/work/client-go/client-go/txnkv/transaction/2pc.go:842 +0x76
github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).doActionOnMutations(0xc00056d340, 0xc000cf5520?, {0x20de590?, 0x365f0a0}, {0x20f2740, 0xc0020c1080})
	/home/runner/work/client-go/client-go/txnkv/transaction/2pc.go:791 +0x6c
github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).pessimisticRollbackMutations(0xc0007ed050?, 0xc0000ba6c0?, {0x20f2740?, 0xc0020c1080?})
	/home/runner/work/client-go/client-go/txnkv/transaction/pessimistic.go:563 +0x17e
github.com/tikv/client-go/v2/txnkv/transaction.actionPessimisticRollback.handleSingleBatch({0x0}, 0xc00056d340, 0xc0007ed050, {{0x4, 0x1, 0x5}, {0x20f2740, 0xc0020c1080}, 0x1})
	/home/runner/work/client-go/client-go/txnkv/transaction/pessimistic.go:527 +0x2f1
github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).doActionOnBatches(0xc00056d340, 0xc0007ed050, {0x20de590?, 0x365f0a0}, {0xc0020bec30?, 0x1, 0xc000090a38?})
	/home/runner/work/client-go/client-go/txnkv/transaction/2pc.go:1056 +0x32f
github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).doActionOnGroupMutations(0xc00056d340, 0xc0007ed050, {0x20de590, 0x365f0a0?}, {0xc0020bec00, 0x1, 0xc000090d80?})
	/home/runner/work/client-go/client-go/txnkv/transaction/2pc.go:1037 +0x1317
github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).doActionOnMutations(0xc00056d340, 0x1a7ad20?, {0x20de590?, 0x365f0a0}, {0x20f2740, 0xc0020c0fc0})
	/home/runner/work/client-go/client-go/txnkv/transaction/2pc.go:800 +0xc7
github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).pessimisticRollbackMutations(0xc000c95440?, 0x1dad5eb?, {0x20f2740?, 0xc0020c0fc0?})
	/home/runner/work/client-go/client-go/txnkv/transaction/pessimistic.go:563 +0x17e
github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).asyncPessimisticRollback.func1()
	/home/runner/work/client-go/client-go/txnkv/transaction/txn.go:1307 +0x5e5
created by github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).asyncPessimisticRollback
	/home/runner/work/client-go/client-go/txnkv/transaction/txn.go:1290 +0x38a
```

The client here may return a nil pointer which will cause panic, we should prevent this case.

https://github.com/tikv/pd/blob/0b362383369e774aa238f119c0f8b6c371c56339/client/client.go#L478-L483

**Comment by binshi-bing** [comment]
Do you have repro steps? The latest PR should have fixed, but if we can verify with repro steps that will give us more confidence.

**Comment by binshi-bing** [comment]
> Do you have repro steps? The latest PR should have fixed, but if we can verify with repro steps that will give us more confidence. @JmPotato

nvm. I saw the test out in the above[ job.](https://github.com/tikv/client-go/actions/runs/4403635107/jobs/7712245145.)
