### ISSUE TITLE
pd leader panic when inject one AZ network partition from other AZs

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#6278]
### What did you do?
https://tcms.pingcap.net/dashboard/executions/plan/1664003
inject one AZ network partition from other AZs
https://tcms.pingcap.net/dashboard/executions/plan/1664003

### What did you expect to see?
no panic

### What did you see instead?
pd leader panic when inject one AZ network partition from other AZs
![7883f9d6-9c24-484a-8fbd-7f2d95148ffc](https://user-images.githubusercontent.com/84712107/230363801-065f19fd-2739-46b3-8f81-ccf2873a9420.jpeg)
http://172.16.4.67:30698/explore?orgId=1&left=%7B%22datasource%22:%22P5F1B1AD64E3A500E%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22tc-pd-2%5C%22,%20testbed%3D%5C%22endless-ha-test-oltp-pitr-tps-1664003-1-67%5C%22%7D%20%21%3D%20%5C%22level%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P5F1B1AD64E3A500E%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D
```
2023-04-06 16:27:53	log="Address:\t10.96.0.10#53\n"
2023-04-06 16:27:53	log="Server:\t\t10.96.0.10\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[google.golang.org/grpc@v1.26.0/server.go:720](http://google.golang.org/grpc@v1.26.0/server.go:720) +0xea\n"
2023-04-06 16:27:51	log="created by [google.golang.org/grpc.(*Server).serveStreams.func1\n](http://google.golang.org/grpc.(*Server).serveStreams.func1/n)"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[google.golang.org/grpc@v1.26.0/server.go:722](http://google.golang.org/grpc@v1.26.0/server.go:722) +0x98\n"
2023-04-06 16:27:51	log="[google.golang.org/grpc.(*Server).serveStreams.func1.1()\n](http://google.golang.org/grpc.(*Server).serveStreams.func1.1()/n)"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[google.golang.org/grpc@v1.26.0/server.go:1313](http://google.golang.org/grpc@v1.26.0/server.go:1313) +0xa25\n"
2023-04-06 16:27:51	log="[google.golang.org/grpc.(*Server).handleStream](http://google.golang.org/grpc.(*Server).handleStream)(0xc0004c5e00, {0x3a52720, 0xc000262000}, 0xc00f791300, 0x0)\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[google.golang.org/grpc@v1.26.0/server.go:1024](http://google.golang.org/grpc@v1.26.0/server.go:1024) +0xd5e\n"
2023-04-06 16:27:51	log="[google.golang.org/grpc.(*Server).processUnaryRPC](http://google.golang.org/grpc.(*Server).processUnaryRPC)(0xc0004c5e00, {0x3a52720, 0xc000262000}, 0xc00f791300, 0xc001429890, 0x4c85800, 0x0)\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[github.com/pingcap/kvproto@v0.0.0-20230317010544-b47a4830141f/pkg/meta_storagepb/meta_storagepb.pb.go:1075](http://github.com/pingcap/kvproto@v0.0.0-20230317010544-b47a4830141f/pkg/meta_storagepb/meta_storagepb.pb.go:1075) +0x138\n"
2023-04-06 16:27:51	log="[github.com/pingcap/kvproto/pkg/meta_storagepb._MetaStorage_Get_Handler](http://github.com/pingcap/kvproto/pkg/meta_storagepb._MetaStorage_Get_Handler)({0x2b9cac0?, 0xc00140c960}, {0x3a43298, 0xc0047ef6e0}, 0xc00cef9ec0, 0xc0012730b0)\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39](http://github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39) +0x1a3\n"
2023-04-06 16:27:51	log="[github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1](http://github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1)({0x3a43298, 0xc0047ef6e0}, {0x2c67300, 0xc00506a1c0}, 0xc00ce1cb00, 0xc00c8fb290)\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[go.etcd.io/etcd@v0.5.0-alpha.5.0.20220915004622-85b640cee793/etcdserver/api/v3rpc/interceptor.go:77](http://go.etcd.io/etcd@v0.5.0-alpha.5.0.20220915004622-85b640cee793/etcdserver/api/v3rpc/interceptor.go:77) +0xc3\n"
2023-04-06 16:27:51	log="[go.etcd.io/etcd/etcdserver/api/v3rpc.newLogUnaryInterceptor.func1](http://go.etcd.io/etcd/etcdserver/api/v3rpc.newLogUnaryInterceptor.func1)({0x3a43298, 0xc0047ef6e0}, {0x2c67300, 0xc00506a1c0}, 0xc00ce1cb00, 0xc004756730)\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34](http://github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34) +0x6f\n"
2023-04-06 16:27:51	log="[github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1](http://github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1)({0x3a43298?, 0xc0047ef6e0?}, {0x2c67300?, 0xc00506a1c0?})\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[go.etcd.io/etcd@v0.5.0-alpha.5.0.20220915004622-85b640cee793/etcdserver/api/v3rpc/interceptor.go:70](http://go.etcd.io/etcd@v0.5.0-alpha.5.0.20220915004622-85b640cee793/etcdserver/api/v3rpc/interceptor.go:70) +0x2a2\n"
2023-04-06 16:27:51	log="[go.etcd.io/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1](http://go.etcd.io/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1)({0x3a43298, 0xc0047ef6e0}, {0x2c67300?, 0xc00506a1c0}, 0x0?, 0xc004756730)\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34](http://github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34) +0x6f\n"
2023-04-06 16:27:51	log="[github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1](http://github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1)({0x3a43298?, 0xc0047ef6e0?}, {0x2c67300?, 0xc00506a1c0?})\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107](http://github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107) +0x87\n"
2023-04-06 16:27:51	log="[github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1](http://github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1)({0x3a43298, 0xc0047ef6e0}, {0x2c67300, 0xc00506a1c0}, 0xc0050b7800?, 0xc004756730)\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31](http://github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31) +0x89\n"
2023-04-06 16:27:51	log="[github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1](http://github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1)({0x3a43298?, 0xc0047ef6e0?}, {0x2c67300?, 0xc00506a1c0?})\n"
2023-04-06 16:27:51	log="\t/go/pkg/mod/[github.com/pingcap/kvproto@v0.0.0-20230317010544-b47a4830141f/pkg/meta_storagepb/meta_storagepb.pb.go:1073](http://github.com/pingcap/kvproto@v0.0.0-20230317010544-b47a4830141f/pkg/meta_storagepb/meta_storagepb.pb.go:1073) +0x78\n"
2023-04-06 16:27:51	log="[github.com/pingcap/kvproto/pkg/meta_storagepb._MetaStorage_Get_Handler.func1](http://github.com/pingcap/kvproto/pkg/meta_storagepb._MetaStorage_Get_Handler.func1)({0x3a43298, 0xc0047ef6e0}, {0x2c67300?, 0xc00506a1c0})\n"
2023-04-06 16:27:51	log="\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/pd/pkg/mcs/meta_storage/server/grpc_service.go:167](http://github.com/pingcap/pd/pkg/mcs/meta_storage/server/grpc_service.go:167) +0x557\n"
2023-04-06 16:27:51	log="[github.com/tikv/pd/pkg/mcs/meta_storage/server.(*Service).Get](http://github.com/tikv/pd/pkg/mcs/meta_storage/server.(*Service).Get)(0xc00140c960, {0x3a43298?, 0xc0047ef6e0?}, 0xc00506a1c0)\n"
2023-04-06 16:27:51	log="goroutine 4511902 [running]:\n"
2023-04-06 16:27:51	log="\n"
2023-04-06 16:27:51	log="[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fe39f7]\n"
2023-04-06 16:27:51	log="panic: runtime error: invalid memory address or nil pointer dereference\n"
2023-04-06 16:27:51	log="[2023/04/06 16:27:51.522 +08:00] [WARN] [retry_interceptor.go:62] [\"retrying of unary invoker failed\"] [target=endpoint://client-825e95cb-3eaa-46ff-a3ea-696f69fed7e1/[tc-pd-2.tc](http://tc-pd-2.tc/)-pd-peer.endless-ha-test-oltp-pitr-tps-1664003-1-67.svc:2379] [attempt=0] [error=\"rpc error: code = Canceled desc = context canceled\"]\n"
```

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v7.1.0-alpha
Edition: Community
Git Commit Hash: da43376badee1063d4c6ca0ce56a39ffef69aeb7
Git Branch: heads/refs/tags/v7.1.0-alpha
UTC Build Time:  2023-04-04 11:32:50
2023-04-06T16:04:08.689+0800	INFO	k8s/client.go:132	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129

**Comment by rleungx** [comment]
The problem only affects the master.
