### ISSUE TITLE
tests: global timestamp fallback in `integrations/tso`

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#6634]
### Which jobs are failing
`/home/runner/work/pd/pd/tests/integrations/tso`

```
2023-06-19T08:41:19.6750574Z panic: global timestamp fallback, new ts (1687164079143, 1) <= the last one (1687164080662, 2861). keyspace: 4294967295, keyspace group: 0
2023-06-19T08:41:19.6750591Z 
2023-06-19T08:41:19.6750703Z goroutine 970548 [running]:
2023-06-19T08:41:19.6750945Z github.com/tikv/pd/client.(*tsoClient).compareAndSwapTS(0xc007255e00, {0x4236587, 0x6}, 0x188d2d0cc27, 0x1, 0x0, 0x1)
2023-06-19T08:41:19.6751144Z 	/home/runner/work/pd/pd/client/tso_dispatcher.go:742 +0x536
2023-06-19T08:41:19.6751408Z github.com/tikv/pd/client.(*tsoClient).processRequests(0xc007255e00, {0x516f020, 0xc0021d1aa0}, {0x4236587, 0x6}, 0xc006c50820, {0x0, 0x0, 0x0})
2023-06-19T08:41:19.6751602Z 	/home/runner/work/pd/pd/client/tso_dispatcher.go:720 +0x4f0
2023-06-19T08:41:19.6751857Z github.com/tikv/pd/client.(*tsoClient).handleDispatcher(0xc007255e00, {0x5189b70?, 0xc006c507d0}, {0x4236587, 0x6}, 0xc006c50820)
2023-06-19T08:41:19.6752051Z 	/home/runner/work/pd/pd/client/tso_dispatcher.go:445 +0x1b25
2023-06-19T08:41:19.6752245Z created by github.com/tikv/pd/client.(*tsoClient).createTSODispatcher
2023-06-19T08:41:19.6752433Z 	/home/runner/work/pd/pd/client/tso_dispatcher.go:290 +0x4f7
2023-06-19T08:41:19.6752605Z FAIL	github.com/tikv/pd/tests/integrations/tso	237.122s
2023-06-19T08:41:19.6752683Z FAIL
2023-06-19T08:41:19.6752977Z make[1]: Leaving directory '/home/runner/work/pd/pd/tests/integrations/tso'
```

### CI link

https://github.com/tikv/pd/actions/runs/5309547422/jobs/9610545886
https://github.com/tikv/pd/actions/runs/5318919915/jobs/9631236217?pr=6626

**Comment by JmPotato** [comment]
Encounter again: https://github.com/tikv/pd/actions/runs/5367692418/jobs/9738042834?pr=6625

**Comment by lhy1024** [comment]
> Encounter again: https://github.com/tikv/pd/actions/runs/5367692418/jobs/9738042834?pr=6625

Can it be closed?

**Comment by JmPotato** [comment]
> > Encounter again: [tikv/pd/actions/runs/5367692418/jobs/9738042834?pr=6625](https://github.com/tikv/pd/actions/runs/5367692418/jobs/9738042834?pr=6625)
> 
> Can it be closed?

Even if it's not a bug, it's still a flasky test. Let's keep this issue open until it's stable.
