### ISSUE TITLE
pd crashed on Phytium

### ISSUE THREAD

**Issue by jebter** [tikv/pd#6899]
### What did you do?

tiup Deployment 7.3.0 
Run tpcc and tpch

### What did you expect to see?
stable running
### What did you see instead?
runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: SIGABRT: abortpthread_create failed: Resource temporarily unavailable

PC=0xfffbf8206490 m=97 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0xfffbf8206490
stack: frame={sp:0xfff7e97be180, fp:0x0} stack=[0xfff7e8dbed08,0xfff7e97be908)
0x0000fff7e97be080:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be090:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0a0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0b0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0c0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0d0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0e0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0f0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be100:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be110:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be120:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be130:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be140:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be150:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be160:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be170:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be180: <0x0000fff7e97be2b0  0x0000fffbf820783c
0x0000fff7e97be190:  0x0000fffbf8352000  0x0000fff7e97bf1d0
0x0000fff7e97be1a0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1b0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1c0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1d0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1e0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1f0:  0x0000fff7e97be2b0  0x0000fffbf8207798
0x0000fff7e97be200:  0x0000fffbf8352000  0x0000fff7e97bf1d0
0x0000fff7e97be210:  0x0000fff7e97be558  0x0000000000000001
0x0000fff7e97be220:  0x0000000000000000  0xfffffffe7fffffff
0x0000fff7e97be230:  0xffffffffffffffff  0xffffffffffffffff
0x0000fff7e97be240:  0xffffffffffffffff  0xffffffffffffffff
0x0000fff7e97be250:  0xffffffffffffffff  0xffffffffffffffff
0x0000fff7e97be260:  0xffffffffffffffff  0xffffffffffffffff
0x0000fff7e97be270:  0xffffffffffffffff  0xffffffffffffffff
runtime: g 0: unknown pc 0xfffbf8206490
stack: frame={sp:0xfff7e97be180, fp:0x0} stack=[0xfff7e8dbed08,0xfff7e97be908)
0x0000fff7e97be080:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be090:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0a0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0b0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0c0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0d0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0e0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be0f0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be100:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be110:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be120:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be130:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be140:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be150:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be160:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be170:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be180: <0x0000fff7e97be2b0  0x0000fffbf820783c
0x0000fff7e97be190:  0x0000fffbf8352000  0x0000fff7e97bf1d0
0x0000fff7e97be1a0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1b0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1c0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1d0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1e0:  0x0000000000000000  0x0000000000000000
0x0000fff7e97be1f0:  0x0000fff7e97be2b0  0x0000fffbf8207798
0x0000fff7e97be200:  0x0000fffbf8352000  0x0000fff7e97bf1d0
0x0000fff7e97be210:  0x0000fff7e97be558  0x0000000000000001
0x0000fff7e97be220:  0x0000000000000000  0xfffffffe7fffffff
0x0000fff7e97be230:  0xffffffffffffffff  0xffffffffffffffff
0x0000fff7e97be240:  0xffffffffffffffff  0xffffffffffffffff
0x0000fff7e97be250:  0xffffffffffffffff  0xffffffffffffffff
0x0000fff7e97be260:  0xffffffffffffffff  0xffffffffffffffff
0x0000fff7e97be270:  0xffffffffffffffff  0xffffffffffffffff

goroutine 64 [GC worker (active)]:
runtime.systemstack_switch()
        /usr/local/go1.20.6/src/runtime/asm_arm64.s:200 +0x8 fp=0x4000506f40 sp=0x4000506f30 pc=0xf7f6e8
runtime.gcBgMarkWorker()
        /usr/local/go1.20.6/src/runtime/mgc.go:1335 +0x210 fp=0x4000506fd0 sp=0x4000506f40 pc=0xf2e270
runtime.goexit()
        /usr/local/go1.20.6/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000506fd0 sp=0x4000506fd0 pc=0xf81cb4
created by runtime.gcBgMarkStartWorkers
        /usr/local/go1.20.6/src/runtime/mgc.go:1199 +0x28

goroutine 1 [chan receive, 5461 minutes]:
### What version of PD are you using (`pd-server -V`)?
v7.3.0

**Comment by jebter** [comment]
CPU:
processor       : 0
model name      : Phytium,S2500/64 C00
BogoMIPS        : 100.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x70
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0x663
CPU revision    : 3

cat /proc/version
Linux version 4.19.90-25.22.v2101.ky10.aarch64 (KYLINSOFT@localhost.localdomain) (gcc version 7.3.0 (GCC)) #1 SMP Thu Nov 24 18:18:43 CST 2022


cat /proc/sys/kernel/threads-max
3124958

**Comment by jebter** [comment]
[pd_stderr.log.zip](https://github.com/tikv/pd/files/12271521/pd_stderr.log.zip)

**Comment by jebter** [comment]
environment problem
