### ISSUE TITLE
panic in TestRollingPolicy_Add

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#7386]
### Which jobs are failing
```
2023-11-15T17:04:55.9143408Z --- FAIL: TestRollingPolicy_Add (0.30s)
2023-11-15T17:04:55.9145312Z     --- FAIL: TestRollingPolicy_Add/test_policy_add#01 (0.10s)
2023-11-15T17:04:55.9147043Z panic: runtime error: index out of range [0] with length 0 [recovered]
2023-11-15T17:04:55.9148402Z 	panic: runtime error: index out of range [0] with length 0
2023-11-15T17:04:55.9149534Z 
2023-11-15T17:04:55.9150160Z goroutine 34 [running]:
2023-11-15T17:04:55.9151067Z testing.tRunner.func1.2({0x720020, 0xc00011c000})
2023-11-15T17:04:55.9152656Z 	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1545 +0x366
2023-11-15T17:04:55.9154041Z testing.tRunner.func1()
2023-11-15T17:04:55.9155164Z 	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1548 +0x630
2023-11-15T17:04:55.9156303Z panic({0x720020?, 0xc00011c000?})
2023-11-15T17:04:55.9157696Z 	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:920 +0x270
2023-11-15T17:04:55.9159081Z github.com/tikv/pd/pkg/window.TestRollingPolicy_Add.func1(0x0?)
2023-11-15T17:04:55.9160653Z 	/home/runner/work/pd/pd/pkg/window/policy_test.go:70 +0x4af
2023-11-15T17:04:55.9161925Z testing.tRunner(0xc000222000, 0xc000216000)
2023-11-15T17:04:55.9163123Z 	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1595 +0x239
2023-11-15T17:04:55.9164267Z created by testing.(*T).Run in goroutine 3
2023-11-15T17:04:55.9165589Z 	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1648 +0x82b
2023-11-15T17:04:55.9166765Z FAIL	github.com/tikv/pd/pkg/window	8.319s
```

### CI link

https://github.com/lhy1024/pd/actions/runs/6880527737/job/18714932638

**Comment by CabinfeverB** [comment]
I run this test 500 times in local env. I think that `time.Sleep` in CI environment has extra time consumption.

**Comment by rleungx** [comment]
I also encounter this panic.
