### ISSUE TITLE
TestTSOAPI/TestForwardResetTS is unstable

### ISSUE THREAD

**Issue by HuSharp** [tikv/pd#7527]
## Flaky Test
TestTSOAPI/TestForwardResetTS panic

### Which jobs are failing
```
api_check.go:29: 
2023-12-11T10:13:46.7676467Z         	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/api_check.go:29
2023-12-11T10:13:46.7678280Z         	            				/home/runner/work/pd/pd/pkg/utils/testutil/api_check.go:157
2023-12-11T10:13:46.7680013Z         	            				/home/runner/work/pd/pd/pkg/utils/testutil/api_check.go:105
2023-12-11T10:13:46.7681895Z         	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/api_test.go:116
2023-12-11T10:13:46.7682922Z         	Error:      	Not equal: 
2023-12-11T10:13:46.7683687Z         	            	expected: 200
2023-12-11T10:13:46.7684464Z         	            	actual  : 500
2023-12-11T10:13:46.7685259Z         	Test:       	TestTSOAPI/TestForwardResetTS
2023-12-11T10:13:46.7686643Z         	Messages:   	resp: PANIC: runtime error: invalid memory address or nil pointer dereference
2023-12-11T10:13:46.7687955Z         	            	goroutine 668 [running]:
2023-12-11T10:13:46.7689439Z         	            	github.com/urfave/negroni.(*Recovery).ServeHTTP.func1()
2023-12-11T10:13:46.7691328Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/recovery.go:159 +0x14f
2023-12-11T10:13:46.7692637Z         	            	panic({0x41a59e0?, 0x6729d80?})
2023-12-11T10:13:46.7694407Z         	            		/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:920 +0x270
2023-12-11T10:13:46.7696519Z         	            	github.com/tikv/pd/pkg/tso.(*AllocatorManager).GetAllocator(0x0, {0x44dc340, 0x6})
2023-12-11T10:13:46.7698378Z         	            		/home/runner/work/pd/pd/pkg/tso/allocator_manager.go:1199 +0xa1
2023-12-11T10:13:46.7700213Z         	            	github.com/tikv/pd/server.(*Handler).ResetTS(0xc001380b40, 0x1d9e0, 0x1, 0x1, 0x0?)
2023-12-11T10:13:46.7701921Z         	            		/home/runner/work/pd/pd/server/handler.go:420 +0x38f
2023-12-11T10:13:46.7704101Z         	            	github.com/tikv/pd/pkg/tso.(*AdminHandler).ResetTS(0xc001616be8, {0x7fbe7c049288?, 0xc0001bf580}, 0xc001b49b00)
2023-12-11T10:13:46.7705975Z         	            		/home/runner/work/pd/pd/pkg/tso/admin.go:98 +0x3b7
2023-12-11T10:13:46.7708828Z         	            	github.com/tikv/pd/server/api.(*serviceMiddlewareBuilder).createHandler.WrapFunc.func1({0x7fbe7c049288, 0xc0001bf580}, 0x108df45?, 0xc0015dadc0)
2023-12-11T10:13:46.7711470Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:56 +0x51
2023-12-11T10:13:46.7714048Z         	            	github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc0015c7b70, {0x7fbe7c049288, 0xc0001bf580}, 0xc002e71bd8?, 0x10cdc8f?)
2023-12-11T10:13:46.7716432Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:29 +0x52
2023-12-11T10:13:46.7719178Z         	            	github.com/urfave/negroni.middleware.ServeHTTP({{0x52b0140?, 0xc0015c7b70?}, 0xc001616c48?}, {0x7fbe7c049288, 0xc0001bf580}, 0x10f81ac?)
2023-12-11T10:13:46.7721673Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x135
2023-12-11T10:13:46.7724464Z         	            	github.com/tikv/pd/server/api.(*rateLimitMiddleware).ServeHTTP(0xc000557960, {0x7fbe7c049288, 0xc0001bf580}, 0xc001b49b00, 0xc0015dada0)
2023-12-11T10:13:46.7726738Z         	            		/home/runner/work/pd/pd/server/api/middleware.go:170 +0x75b
2023-12-11T10:13:46.7729372Z         	            	github.com/urfave/negroni.middleware.ServeHTTP({{0x52b0820?, 0xc000557960?}, 0xc001616c30?}, {0x7fbe7c049288, 0xc0001bf580}, 0x10f81ac?)
2023-12-11T10:13:46.7731844Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x135
2023-12-11T10:13:46.7734701Z         	            	github.com/tikv/pd/server/api.(*auditMiddleware).ServeHTTP(0xc000557958, {0x7fbe7c049288, 0xc0001bf580}, 0xc001b49b00, 0xc0015dad80)
2023-12-11T10:13:46.7736868Z         	            		/home/runner/work/pd/pd/server/api/middleware.go:150 +0xc34
2023-12-11T10:13:46.7739492Z         	            	github.com/urfave/negroni.middleware.ServeHTTP({{0x52b0840?, 0xc000557958?}, 0xc001616c18?}, {0x7fbe7c049288, 0xc0001bf580}, 0x10f81ac?)
2023-12-11T10:13:46.7741951Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x135
2023-12-11T10:13:46.7744795Z         	            	github.com/tikv/pd/server/api.(*requestInfoMiddleware).ServeHTTP(0xc000557950, {0x7fbe7c049288, 0xc0001bf580}, 0xc001b49a00, 0xc0015dad40)
2023-12-11T10:13:46.7747058Z         	            		/home/runner/work/pd/pd/server/api/middleware.go:76 +0x12ad
2023-12-11T10:13:46.7749692Z         	            	github.com/urfave/negroni.middleware.ServeHTTP({{0x52b0860?, 0xc000557950?}, 0xc001616c00?}, {0x7fbe7c049288, 0xc0001bf580}, 0x408ec60?)
2023-12-11T10:13:46.7752172Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x135
2023-12-11T10:13:46.7754422Z         	            	github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc00162cf90, {0x7fbe7c049288?, 0xc0001bf578}, 0x0?)
2023-12-11T10:13:46.7756850Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:96 +0x1b9
2023-12-11T10:13:46.7759122Z         	            	github.com/gorilla/mux.(*Router).ServeHTTP(0xc0013f5d40, {0x7fbe7c049288, 0xc0001bf578}, 0xc001b49800)
2023-12-11T10:13:46.7761450Z         	            		/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x362
2023-12-11T10:13:46.7763833Z         	            	github.com/tikv/pd/server/api.NewHandler.Wrap.func21({0x7fbe7c049288, 0xc0001bf578}, 0x108df45?, 0xc0015dad20)
2023-12-11T10:13:46.7766164Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:46 +0x67
2023-12-11T10:13:46.7768686Z         	            	github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc001616d08, {0x7fbe7c049288, 0xc0001bf578}, 0x10f81ac?, 0x10fca95?)
2023-12-11T10:13:46.7771103Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:29 +0x52
2023-12-11T10:13:46.7774095Z         	            	github.com/urfave/negroni.middleware.ServeHTTP({{0x52b0140?, 0xc001616d08?}, 0xc001616d50?}, {0x7fbe7c049288, 0xc0001bf578}, 0x10f81ac?)
2023-12-11T10:13:46.7776632Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x135
2023-12-11T10:13:46.7779671Z         	            	github.com/tikv/pd/pkg/utils/apiutil/serverapi.(*redirector).ServeHTTP(0xc001656e00, {0x7fbe7c049288, 0xc0001bf578}, 0xc001b49800, 0xc0015dad00)
2023-12-11T10:13:46.7782417Z         	            		/home/runner/work/pd/pd/pkg/utils/apiutil/serverapi/middleware.go:181 +0x2cd
2023-12-11T10:13:46.7785271Z         	            	github.com/urfave/negroni.middleware.ServeHTTP({{0x52b0120?, 0xc001656e00?}, 0xc001616d38?}, {0x7fbe7c049288, 0xc0001bf578}, 0x10f81ac?)
2023-12-11T10:13:46.7787802Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x135
2023-12-11T10:13:46.7790973Z         	            	github.com/tikv/pd/pkg/utils/apiutil/serverapi.(*runtimeServiceValidator).ServeHTTP(0xc001646440, {0x7fbe7c049288, 0xc0001bf578}, 0xc000100000?, 0xc0015dace0)
2023-12-11T10:13:46.7793773Z         	            		/home/runner/work/pd/pd/pkg/utils/apiutil/serverapi/middleware.go:45 +0x172
2023-12-11T10:13:46.7796615Z         	            	github.com/urfave/negroni.middleware.ServeHTTP({{0x52b0880?, 0xc001646440?}, 0xc001616d20?}, {0x7fbe7c049288, 0xc0001bf578}, 0x408ec60?)
2023-12-11T10:13:46.7799101Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x135
2023-12-11T10:13:46.7801310Z         	            	github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc00162d2f0, {0x7fbe7c049288?, 0xc0001bf570}, 0x0?)
2023-12-11T10:13:46.7803575Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:96 +0x1b9
2023-12-11T10:13:46.7805894Z         	            	github.com/gorilla/mux.(*Router).ServeHTTP(0xc001484180, {0x7fbe7c049288, 0xc0001bf570}, 0xc001b49600)
2023-12-11T10:13:46.7808093Z         	            		/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x362
2023-12-11T10:13:46.7810354Z         	            	github.com/gorilla/mux.(*Router).ServeHTTP(0xc0013f5c80, {0x7fbe7c049288, 0xc0001bf570}, 0xc001b49400)
2023-12-11T10:13:46.7812536Z         	            		/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0x362
2023-12-11T10:13:46.7815153Z         	            	github.com/urfave/negroni.(*Negroni).UseHandler.Wrap.func1({0x7fbe7c049288, 0xc0001bf570}, 0x108df45?, 0xc0015daca0)
2023-12-11T10:13:46.7817526Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:46 +0x67
2023-12-11T10:13:46.7819892Z         	            	github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc001616e70, {0x7fbe7c049288, 0xc0001bf570}, 0x0?, 0x0?)
2023-12-11T10:13:46.7822166Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:29 +0x52
2023-12-11T10:13:46.7825199Z         	            	github.com/urfave/negroni.middleware.ServeHTTP({{0x52b0140?, 0xc001616e70?}, 0xc001616ea0?}, {0x7fbe7c049288, 0xc0001bf570}, 0xc00146d1a0?)
2023-12-11T10:13:46.7827800Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x135
2023-12-11T10:13:46.7830575Z         	            	github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc0012b5d60, {0x7fbe7c049288, 0xc0001bf570}, 0xc001b49400, 0xc0015dac80)
2023-12-11T10:13:46.7833004Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/recovery.go:193 +0xe2
2023-12-11T10:13:46.7835823Z         	            	github.com/urfave/negroni.middleware.ServeHTTP({{0x52b0340?, 0xc0012b5d60?}, 0xc001616e88?}, {0x7fbe7c049288, 0xc0001bf570}, 0xc002e05200?)
2023-12-11T10:13:46.7838358Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:38 +0x135
2023-12-11T10:13:46.7840679Z         	            	github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc00146d1a0, {0x52be530?, 0xc0004aec40}, 0xc002e05200?)
2023-12-11T10:13:46.7842937Z         	            		/home/runner/go/pkg/mod/github.com/urfave/negroni@v0.3.0/negroni.go:96 +0x1b9
2023-12-11T10:13:46.7844883Z         	            	net/http.(*ServeMux).ServeHTTP(0x52be530?, {0x52be530, 0xc0004aec40}, 0xc001b49400)
2023-12-11T10:13:46.7846791Z         	            		/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2514 +0xbd
2023-12-11T10:13:46.7849035Z         	            	go.etcd.io/etcd/embed.(*accessController).ServeHTTP(0xc0001a6870, {0x52be530, 0xc0004aec40}, 0xc001b49400)
2023-12-11T10:13:46.7852052Z         	            		/home/runner/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20220915004622-85b640cee793/embed/serve.go:381 +0x94e
2023-12-11T10:13:46.7854526Z         	            	net/http.serverHandler.ServeHTTP({0x52b65f8?}, {0x52be530, 0xc0004aec40}, 0xc001b49400)
2023-12-11T10:13:46.7856503Z         	            		/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2938 +0x2a2
2023-12-11T10:13:46.7858115Z         	            	net/http.(*conn).serve(0xc001b5afc0, {0x52cbd00, 0xc001b53920})
2023-12-11T10:13:46.7859902Z         	            		/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2009 +0xc25
2023-12-11T10:13:46.7861409Z         	            	created by net/http.(*Server).Serve in goroutine 311
2023-12-11T10:13:46.7863186Z         	            		/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:3086 +0x80d
```

### CI link
https://github.com/tikv/pd/actions/runs/7165822972/job/19508584652?pr=7372

**Comment by HuSharp** [comment]
false issue, result by specific pr...
