### ISSUE TITLE
tidb panic when scale in pd from 6 to 3

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#7760]
### What did you do?
1、scale out pd from 3 to 6
2、scale in pd from 6 to 3

### What did you expect to see?
no painc

### What did you see instead?
tidb panic

2024-01-23 12:39:28	log="2024-01-23T12:39:28.886543139+08:00 stderr F \t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:243](http://github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:243) +0x585"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886536764+08:00 stderr F created by [github.com/tikv/client-go/v2/tikv.NewKVStore](http://github.com/tikv/client-go/v2/tikv.NewKVStore) in goroutine 1"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886530142+08:00 stderr F \t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:589](http://github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:589) +0x1ef"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886523844+08:00 stderr F [github.com/tikv/client-go/v2/tikv.(*KVStore).safeTSUpdater(0xc000e19ce0)](http://github.com/tikv/client-go/v2/tikv.(*KVStore).safeTSUpdater(0xc000e19ce0))"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886516936+08:00 stderr F \t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:596](http://github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:596) +0x4a"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886510506+08:00 stderr F [github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS](http://github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS)(0xc000e19ce0, {0x64174b8?, 0xc000708000?})"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886503905+08:00 stderr F \t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:727](http://github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:727) +0x92"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886497793+08:00 stderr F [github.com/tikv/client-go/v2/tikv.(*KVStore).updateGlobalTxnScopeTSFromPD](http://github.com/tikv/client-go/v2/tikv.(*KVStore).updateGlobalTxnScopeTSFromPD)(0xc000e19ce0, {0x64174b8, 0xc000708000})"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886491476+08:00 stderr F \t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:693](http://github.com/tikv/client-go/v2@v2.0.8-0.20231227070846-61c486af13a5/tikv/kv.go:693) +0x46"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886481414+08:00 stderr F [github.com/tikv/client-go/v2/tikv.(*KVStore).getMinResolvedTSByStoresIDs](http://github.com/tikv/client-go/v2/tikv.(*KVStore).getMinResolvedTSByStoresIDs)(0x0?, {0x64174b8?, 0xc000708000?}, {0x0?, 0x7ff0681065d0?, 0x7ff0b2276878?})"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886474765+08:00 stderr F \t/go/pkg/mod/[github.com/tikv/pd/client@v0.0.0-20240109100024-dd8df25316e9/http/interface.go:749](http://github.com/tikv/pd/client@v0.0.0-20240109100024-dd8df25316e9/http/interface.go:749) +0x167"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886467608+08:00 stderr F [github.com/tikv/pd/client/http.(*client).GetMinResolvedTSByStoresIDs](http://github.com/tikv/pd/client/http.(*client).GetMinResolvedTSByStoresIDs)(0x13?, {0x64174b8, 0xc000708000}, {0x0?, 0x13?, 0xc163ee985a977855?})"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886461023+08:00 stderr F \t/go/pkg/mod/[github.com/tikv/pd/client@v0.0.0-20240109100024-dd8df25316e9/http/client.go:462](http://github.com/tikv/pd/client@v0.0.0-20240109100024-dd8df25316e9/http/client.go:462) +0x92"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886454431+08:00 stderr F [github.com/tikv/pd/client/http.(*client).request](http://github.com/tikv/pd/client/http.(*client).request)(0x0?, {0x64174b8?, 0xc000708000?}, 0x271ac85?, {0x0?, 0x0?, 0x0?})"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886446988+08:00 stderr F \t/go/pkg/mod/[github.com/tikv/pd/client@v0.0.0-20240109100024-dd8df25316e9/http/client.go:184](http://github.com/tikv/pd/client@v0.0.0-20240109100024-dd8df25316e9/http/client.go:184) +0x1ba"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886426927+08:00 stderr F [github.com/tikv/pd/client/http.(*clientInner).requestWithRetry](http://github.com/tikv/pd/client/http.(*clientInner).requestWithRetry)(0xc000faa400, {0x64174b8?, 0xc000708000}, 0xc003abb720, {0x0, 0x0, 0x0})"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886401748+08:00 stderr F \t/go/pkg/mod/[github.com/tikv/pd/client@v0.0.0-20240109100024-dd8df25316e9/http/client.go:173](http://github.com/tikv/pd/client@v0.0.0-20240109100024-dd8df25316e9/http/client.go:173) +0x9f8"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886393695+08:00 stderr F [github.com/tikv/pd/client/http.(*clientInner).requestWithRetry.func1()](http://github.com/tikv/pd/client/http.(*clientInner).requestWithRetry.func1())"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886386189+08:00 stderr F goroutine 33 [running]:"
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886377561+08:00 stderr F "
2024-01-23 12:39:28	log="2024-01-23T12:39:28.886337968+08:00 stderr F panic: runtime error: index out of range [4] with length 3"

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v8.0.0-alpha
Edition: Community
Git Commit Hash: 6929c15e379319f321be58ce6cc0ec6f845a97c4
Git Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time:  2024-01-22 11:37:02
2024-01-23T11:50:19.632+0800

**Comment by JmPotato** [comment]
Fixed in master and only exists in v7.6.0.
