### ISSUE TITLE
`TestClientClusterIDCheck` panic

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#7763]
### Which jobs are failing
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29ef8c0]

goroutine 138 [running]:
testing.tRunner.func1.2({0x2e935c0, 0x5113d90})
	/data/nvme0n1/ryan/sdk/go1.21.6/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	/data/nvme0n1/ryan/sdk/go1.21.6/src/testing/testing.go:1548 +0x397
panic({0x2e935c0?, 0x5113d90?})
	/data/nvme0n1/ryan/sdk/go1.21.6/src/runtime/panic.go:914 +0x21f
github.com/tikv/pd/tests/integrations/client_test.TestClientClusterIDCheck(0x0?)
	/data/nvme0n1/ryan/workspace/pd/tests/integrations/client/client_test.go:85 +0x3a0
testing.tRunner(0xc000c784e0, 0x3b409c8)
	/data/nvme0n1/ryan/sdk/go1.21.6/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/data/nvme0n1/ryan/sdk/go1.21.6/src/testing/testing.go:1648 +0x3ad
FAIL	github.com/tikv/pd/tests/integrations/client	35.483s
```

**Comment by HuSharp** [comment]
closed by https://github.com/tikv/pd/issues/7770
