### ISSUE TITLE
TestRegionSyncer is unstable

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#8350]
### Which jobs are failing
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b04333]

goroutine 4857726 [running]:
github.com/tikv/pd/tests.(*TestServer).GetServer(0x0)
	/home/runner/work/pd/pd/tests/cluster.go:217 +0x53
github.com/tikv/pd/tests/server/region_syncer_test.TestRegionSyncer.func6()
	/home/runner/work/pd/pd/tests/server/region_syncer/region_syncer_test.go:146 +0x1b
github.com/stretchr/testify/assert.Eventually.func1()
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/assert/assertions.go:1852 +0x22
created by github.com/stretchr/testify/assert.Eventually in goroutine 81
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/assert/assertions.go:1852 +0x21e
```

### CI link

https://github.com/tikv/pd/actions/runs/9737924850/job/26870705813

**Comment by rleungx** [comment]
Close it since it won't panic.
