### ISSUE TITLE
panic in TestFollowerForward

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#8642]
### Which jobs are failing
```
2024-09-23T03:39:56.2313772Z === RUN   TestAPI/TestFollowerForward
2024-09-23T03:39:56.2314415Z === NAME  TestAPI
2024-09-23T03:39:56.2345476Z     testutil.go:337: start test TestFollowerForward in pd mode
........................
2024-09-23T03:39:57.1908097Z panic: failed to find local ID in cluster members
2024-09-23T03:39:57.1908159Z 
2024-09-23T03:39:57.1908432Z goroutine 215483 [running]:
2024-09-23T03:39:57.1909237Z go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc00327fe10, {0x5bb896b?, 0x57?, 0x0?})
2024-09-23T03:39:57.1909887Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x9f
2024-09-23T03:39:57.1910483Z go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00327fe10, {0xc007086780, 0x2, 0x2})
2024-09-23T03:39:57.1911126Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x5c2
2024-09-23T03:39:57.1911803Z go.uber.org/zap.(*Logger).Panic(0x3840ef566c97b889?, {0x4a3c100, 0x2a}, {0xc007086780, 0x2, 0x2})
2024-09-23T03:39:57.1912505Z 	/home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:285 +0x68
2024-09-23T03:39:57.1913349Z go.etcd.io/etcd/server/v3/etcdserver/api/membership.(*RaftCluster).IsLocalMemberLearner(0xc007331620)
2024-09-23T03:39:57.1914232Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/etcdserver/api/membership/cluster.go:859 +0x371
2024-09-23T03:39:57.1914841Z go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).IsLearner(0xc003e19500)
2024-09-23T03:39:57.1915857Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/etcdserver/server.go:2822 +0x45
2024-09-23T03:39:57.1917023Z go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.(*maintenanceServer).Status(0xc0029c09c0, {0x2caa44c?, 0xc0008ff440?}, 0xc0058b9178?)
2024-09-23T03:39:57.1918177Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/etcdserver/api/v3rpc/maintenance.go:232 +0x202
2024-09-23T03:39:57.1919360Z go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.(*authMaintenanceServer).Status(0xc007992978, {0x585af70, 0xc004171830}, 0x49c45ae?)
2024-09-23T03:39:57.1920265Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/etcdserver/api/v3rpc/maintenance.go:310 +0x54
2024-09-23T03:39:57.1921290Z go.etcd.io/etcd/api/v3/etcdserverpb._Maintenance_Status_Handler.func1({0x585af70, 0xc004171830}, {0x48abbe0?, 0xc0032f02c0})
2024-09-23T03:39:57.1922067Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd/api/v3@v3.5.15/etcdserverpb/rpc.pb.go:7499 +0x83
2024-09-23T03:39:57.1923881Z github.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3({0x585af70, 0xc004171830}, {0x48abbe0, 0xc0032f02c0}, 0xc0032f02e0, 0xc00b37d3f8)
2024-09-23T03:39:57.1925180Z 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xbc
2024-09-23T03:39:57.1926319Z go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.Server.ChainUnaryServer.func6.1({0x585af70, 0xc004171830}, {0x48abbe0, 0xc0032f02c0})
2024-09-23T03:39:57.1927330Z 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0xd1
2024-09-23T03:39:57.1928840Z go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.Server.newUnaryInterceptor.func4({0x585af70, 0xc004171830}, {0x48abbe0, 0xc0032f02c0}, 0x0?, 0xc009f8ff40)
2024-09-23T03:39:57.1929965Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/etcdserver/api/v3rpc/interceptor.go:71 +0x2c2
2024-09-23T03:39:57.1931215Z go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.Server.ChainUnaryServer.func6.1({0x585af70, 0xc004171830}, {0x48abbe0, 0xc0032f02c0})
2024-09-23T03:39:57.1932262Z 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0xd1
2024-09-23T03:39:57.1933643Z go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.Server.newLogUnaryInterceptor.func3({0x585af70?, 0xc004171830}, {0x48abbe0?, 0xc0032f02c0}, 0xc0032f02e0, 0xc009f8ff80)
2024-09-23T03:39:57.1934600Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.15/etcdserver/api/v3rpc/interceptor.go:78 +0xc9
2024-09-23T03:39:57.1936118Z go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.Server.ChainUnaryServer.func6({0x585af70, 0xc004171830}, {0x48abbe0, 0xc0032f02c0}, 0xc0032f02e0, 0xc00b37d3f8)
2024-09-23T03:39:57.1937283Z 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x22d
2024-09-23T03:39:57.1938424Z go.etcd.io/etcd/api/v3/etcdserverpb._Maintenance_Status_Handler({0x483e1a0?, 0xc007992978}, {0x585af70, 0xc004171830}, 0xc007086700, 0xc00375ed80)
2024-09-23T03:39:57.1939260Z 	/home/runner/go/pkg/mod/go.etcd.io/etcd/api/v3@v3.5.15/etcdserverpb/rpc.pb.go:7501 +0x1c4
2024-09-23T03:39:57.1940460Z google.golang.org/grpc.(*Server).processUnaryRPC(0xc0027ce600, {0x585af70, 0xc0041717a0}, {0x5869c80, 0xc002ea7040}, 0xc006419c20, 0xc0056d63c0, 0x6e364d8, 0x0)
2024-09-23T03:39:57.1941115Z 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1386 +0x19ad
2024-09-23T03:39:57.1941910Z google.golang.org/grpc.(*Server).handleStream(0xc0027ce600, {0x5869c80, 0xc002ea7040}, 0xc006419c20)
2024-09-23T03:39:57.1942660Z 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1797 +0x1a52
2024-09-23T03:39:57.1943159Z google.golang.org/grpc.(*Server).serveStreams.func2.1()
2024-09-23T03:39:57.1943797Z 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1027 +0x15d
2024-09-23T03:39:57.1944507Z created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 215441
2024-09-23T03:39:57.1945347Z 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1038 +0x225
2024-09-23T03:40:30.2073536Z run all tasks takes 1m30.295012206s
```

### CI link
https://github.com/tikv/pd/actions/runs/10987255858/job/30501833484?pr=8623

**Comment by lhy1024** [comment]
https://github.com/tikv/pd/actions/runs/11029325518/job/30631489180?pr=4903
