### ISSUE TITLE
TestPreparingProgress is flaky

### ISSUE THREAD

**Issue by okJiang** [tikv/pd#8693]
### Which jobs are failing

TestPreparingProgress

```
    api_test.go:1108: 
        	Error Trace:	/home/runner/work/pd/pd/tests/server/api/api_test.go:1108
        	            				/home/runner/work/pd/pd/tests/server/api/api_test.go:1012
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 200
        	Test:       	TestPreparingProgress
```

### CI link

https://github.com/tikv/pd/actions/runs/11287900664/job/31394644984?pr=8685

**Comment by okJiang** [comment]
https://github.com/tikv/pd/actions/runs/11331437937/job/31511453095?pr=8699

**Comment by lhy1024** [comment]
https://github.com/tikv/pd/actions/runs/11360417425/job/31599485517

**Comment by lhy1024** [comment]
https://github.com/tikv/pd/actions/runs/11591672880/job/32271910289

**Comment by okJiang** [comment]
https://github.com/tikv/pd/actions/runs/11607949077/job/32322275766?pr=8757

**Comment by lhy1024** [comment]
https://github.com/tikv/pd/actions/runs/11885726674/job/33115845079 again

**Comment by lhy1024** [comment]
https://github.com/tikv/pd/actions/runs/12023687193/job/33517970286?pr=8855 again

**Comment by okJiang** [comment]
https://github.com/tikv/pd/actions/runs/12556798438/job/35010305779?pr=8963

**Comment by lhy1024** [comment]
```
--- FAIL: TestPreparingProgress (10.93s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x429f40b]

goroutine 250 [running]:
testing.tRunner.func1.2({0x4896480, 0x7089ec0})
	/opt/hostedtoolcache/go/1.23.4/x64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.23.4/x64/src/testing/testing.go:1635 +0x6b6
panic({0x4896480?, 0x7089ec0?})
	/opt/hostedtoolcache/go/1.23.4/x64/src/runtime/panic.go:785 +0x132
github.com/tikv/pd/tests.MustPutStore(0xc00077f100, 0xc0013efce0, 0xc0004c2aa0)
	/home/runner/work/pd/pd/tests/testutil.go:214 +0x6eb
github.com/tikv/pd/tests/server/api.TestPreparingProgress(0xc0004de9c0)
	/home/runner/work/pd/pd/tests/server/api/api_test.go:1035 +0x1b6d
testing.tRunner(0xc0004de9c0, 0x55a0c80)
	/opt/hostedtoolcache/go/1.23.4/x64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.4/x64/src/testing/testing.go:1743 +0x826
run all tasks takes 3m16.348446623s
```
https://github.com/tikv/pd/actions/runs/12824827393/job/35761655346
