### ISSUE TITLE
TestResignTSOPrimaryForward is flaky

### ISSUE THREAD

**Issue by okJiang** [tikv/pd#8737]
### Which jobs are failing

```
server_test.go:234: 
        	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:234
        	            				/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:323
        	Error:      	Received unexpected error:
        	            	[PD:etcd:ErrStartEtcd]listen tcp 127.0.0.1:39627: bind: address already in use: listen tcp 127.0.0.1:39627: bind: address already in use
        	            	github.com/pingcap/errors.AddStack
        	            		/home/runner/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174
        	            	github.com/pingcap/errors.(*Error).GenWithStackByCause
        	            		/home/runner/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:307
        	            	github.com/tikv/pd/server.(*Server).startEtcd
        	            		/home/runner/work/pd/pd/server/server.go:329
        	            	github.com/tikv/pd/server.(*Server).Run
        	            		/home/runner/work/pd/pd/server/server.go:618
        	            	github.com/tikv/pd/tests.(*TestServer).Run
        	            		/home/runner/work/pd/pd/tests/cluster.go:127
        	            	github.com/tikv/pd/tests.RunServer.func1
        	            		/home/runner/work/pd/pd/tests/cluster.go:577
        	            	runtime.goexit
        	            		/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/asm_amd64.s:1700
        	            	github.com/tikv/pd/tests.RunServers
        	            		/home/runner/work/pd/pd/tests/cluster.go:589
        	            	github.com/tikv/pd/tests.(*TestCluster).RunInitialServers
        	            		/home/runner/work/pd/pd/tests/cluster.go:601
        	            	github.com/tikv/pd/tests/integrations/mcs/tso.NewAPIServerForward
        	            		/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:233
        	            	github.com/tikv/pd/tests/integrations/mcs/tso.TestResignTSOPrimaryForward
        	            		/home/runner/work/pd/pd/tests/integrations/mcs/tso/server_test.go:323
        	            	testing.tRunner
        	            		/opt/hostedtoolcache/go/1.23.2/x64/src/testing/testing.go:[169](https://github.com/tikv/pd/actions/runs/11454903722/job/31869908930?pr=8732#step:4:170)0
        	            	runtime.goexit
        	            		/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/asm_amd64.s:[170](https://github.com/tikv/pd/actions/runs/11454903722/job/31869908930?pr=8732#step:4:171)0
        	Test:       	TestResignTSOPrimaryForward
--- FAIL: TestResignTSOPrimaryForward (0.15s)
```

### CI link

https://github.com/tikv/pd/actions/runs/11454903722/job/31869908930?pr=8732

**Comment by rleungx** [comment]
the same as https://github.com/tikv/pd/issues/8726

**Comment by okJiang** [comment]
## Flaky Test
### Which jobs are failing
```text
panic: test timed out after 5m0s
	running tests:
		TestResignTSOPrimaryForward (5m0s)
github.com/tikv/pd/tests/integrations/mcs/tso.TestMain(...)
	/home/prow/go/src/github.com/tikv/pd/tests/integrations/mcs/tso/server_test.go:59
```
### New CI link
- https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10275/pull-unit-test-next-gen-3/2031625125907927040
### Reason for failure (if possible)

### Anything else
- triage-key: `testresigntsoprimaryforward`
- test: `TestResignTSOPrimaryForward`

**Comment by okJiang** [comment]
## Flaky Test
### Which jobs are failing
```text
[2026/03/12 10:16:20.048 +08:00] [INFO] [raft] [zap_raft.go:77] ["d2f7306e7b961a02 [logterm: 1, index: 3] sent MsgPreVote request to 5573a99b6672745 at term 1"]
[2026/03/12 10:16:20.048 +08:00] [INFO] [raft] [zap_raft.go:77] ["d2f7306e7b961a02 [logterm: 1, index: 3] sent MsgPreVote request to 6c17b74a7766bc2b at term 1"]
coverage: 7.5% of statements in ../../...
panic: test timed out after 5m0s
	running tests:
		TestResignAPIPrimaryForward (5m0s)
goroutine 26410 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2682 +0x605
created by time.goFunc
	/usr/local/go/src/time/sleep.go:215 +0x45
goroutine 1 [chan receive, 5 minutes]:
```
### New CI link
https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10212/pull-unit-test-next-gen-3/2031913362786357248
### Reason for failure (if possible)

### Anything else
test=TestResignTSOPrimaryForward signatures=TIMEOUT_PANIC,PANIC
