### ISSUE TITLE
PD panic when updateSubTree

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#8915]
## Bug Report

```
goroutine 1301574582 [running]:
github.com/tikv/pd/server/core.(*RegionsInfo).UpdateSubTree(0xc0004181c0, 0xc0311a7e00, 0xc016631a00,
{0x0, 0x0, 0x10?}
, 0)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/core/region.go:868 +0x15b
github.com/tikv/pd/server/core.(*RegionsInfo).AtomicCheckAndPutRegion(0xc0004181c0, 0xc0311a7e00)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/core/region.go:759 +0x1f4
github.com/tikv/pd/server/cluster.(*RaftCluster).processRegionHeartbeat(0xc000f60140, 0xc0311a7e00)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/cluster/cluster.go:877 +0x67d
github.com/tikv/pd/server/cluster.(*RaftCluster).HandleRegionHeartbeat(0xc000f60140, 0xc004a05760?)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/cluster/cluster_worker.go:36 +0x25
github.com/tikv/pd/server.(*GrpcServer).RegionHeartbeat(0xc002a26000,
{0x38761f8?, 0xc025a13a00}
)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/server/grpc_service.go:965 +0xcc5
github.com/pingcap/kvproto/pkg/pdpb._PD_RegionHeartbeat_Handler(
{0x2a6cd60?, 0xc002a26000}, {0x38722b0?, 0xc0221ec150})
/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20221104101942-09d82b914df1/pkg/pdpb/pdpb.pb.go:8144 +0xa2
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1({0x2a6cd60?, 0xc002a26000}
,
{0x38722b0?, 0xc0221ec150}
)
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:71 +0x89
```

### What did you do?
no panic

### What did you expect to see?
panic

### What version of PD are you using (`pd-server -V`)?

v6.5.3

**Comment by rleungx** [comment]
release-7.1 also has this issue.

**Comment by bufferflies** [comment]
fixed
