### ISSUE TITLE
`TestDisableSchedulingServiceFallback` is flaky

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#8926]
### Which jobs are failing
```
    server_test.go:109: 
        	Error Trace:	/home/runner/work/pd/pd/tests/integrations/mcs/scheduling/server_test.go:109
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestServerTestSuite/TestAllocIDAfterLeaderChange
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42186f0]

goroutine 450604 [running]:
github.com/tikv/pd/tests/integrations/mcs/scheduling.(*serverTestSuite).TestDisableSchedulingServiceFallback.func1()
	/home/runner/work/pd/pd/tests/integrations/mcs/scheduling/server_test.go:262 +0x50
github.com/stretchr/testify/assert.Eventually.func1()
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x34
created by github.com/stretchr/testify/assert.Eventually in goroutine 450613
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x3d6
```

### CI link
https://github.com/tikv/pd/actions/runs/12367690342/job/34516396487?pr=8887

**Comment by bufferflies** [comment]
let me fix it

**Comment by okJiang** [comment]
## Flaky Test
### Which jobs are failing
```text
=== RUN   TestServerTestSuite
Error Trace: /home/prow/go/src/github.com/tikv/pd/tests/testutil.go:174
             /home/prow/go/src/github.com/tikv/pd/tests/integrations/mcs/router/server_test.go:81
Error:       Received unexpected error:
             listen tcp 127.0.0.1:35377: bind: address already in use
Test:        TestServerTestSuite
--- FAIL: TestServerTestSuite (4.06s)
```
### New CI link
https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10212/pull-unit-test-next-gen-3/2031204676497575936
https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10259/pull-unit-test-next-gen-3/2031256501271662592
### Reason for failure (if possible)

### Anything else
